Repository KallistiOS/KallistiOS, pull requests merged in 2023-09, with the labels that each got.

#293 Fix vmu_set_icon_shape omitted on DC instead of NAOMI
  kernel/arch/dreamcast/hardware/maple/vmu.c
Labels: bug

#302 wav2adpcm: Fixed 2 warnings, WAV verification errors mapped to stderr
  utils/wav2adpcm/wav2adpcm.c
Labels: update

#300 Modified thd_each() to support early exit + retval
  include/kos/thread.h
  kernel/thread/thread.c
Labels: enhancement

#298 Enabled atomics support in environ_dreamcast.h
  environ_dreamcast.sh
Labels: enhancement, toolchain

#299 Added Makefile for YUV PVR demos
  examples/dreamcast/pvr/Makefile
  examples/dreamcast/pvr/yuv_converter/Makefile
Labels: update

#306 Added posix/sysconf.c to implement sysconf()
  kernel/libc/posix/Makefile
  kernel/libc/posix/sysconf.c
Labels: enhancement

#301 Initial C11 libatomic GCC builtin implementation
  doc/CHANGELOG
  examples/dreamcast/basic/threading/Makefile
  examples/dreamcast/basic/threading/atomics/Makefile
  examples/dreamcast/basic/threading/atomics/atomics.c
  kernel/libc/c11/Makefile
  kernel/libc/c11/atomics.c
Labels: enhancement, toolchain

#111 Enable TLS Support for C/C++
  doc/CHANGELOG
  environ_dreamcast.sh
  examples/dreamcast/basic/threading/Makefile
  examples/dreamcast/basic/threading/compiler_tls/Makefile
  examples/dreamcast/basic/threading/compiler_tls/compiler_tls.c
  include/kos/thread.h
  kernel/thread/thread.c
  utils/cmake/dreamcast.toolchain.cmake
  utils/dc-chain/scripts/gcc-pass1.mk
  utils/dc-chain/scripts/gcc-pass2.mk
  utils/ldscripts/shlelf-naomi.xc
  utils/ldscripts/shlelf.xc
Labels: enhancement, toolchain

#310 CMake toolchain support for C11/C++11 atomics
  utils/cmake/dreamcast.toolchain.cmake
Labels: enhancement, toolchain

#309 Add new "WinXP-Latest" toolchain configuration
  utils/dc-chain/config/README.md
  utils/dc-chain/config/config.mk.winxp-latest.sample
  utils/dc-chain/patches/arm-Darwin/gcc-9.5.0-kos.diff
  utils/dc-chain/patches/gcc-9.5.0-kos.diff
Labels: toolchain

#307 Vmu extra blocks
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/maple/vmu.h
Labels: enhancement

#313 Rework once controls, once again.
  kernel/thread/once.c
Labels: enhancement

#312 Added repro for multithreaded kthread_once deadlock issue to test
  examples/dreamcast/basic/threading/once/once_test.c
Labels: enhancement
