Repository KallistiOS/KallistiOS, pull requests merged in 2023-08, with the labels that each got.

#246 Defines for memory areas
  include/kos.h
  kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c
  kernel/arch/dreamcast/hardware/maple/maple_queue.c
  kernel/arch/dreamcast/hardware/maple/maple_utils.c
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/arch/memory.h
  kernel/arch/dreamcast/include/dc/pvr.h
  kernel/arch/dreamcast/kernel/init.c
Labels: enhancement, cleanup

#265 Fix: MEM_AREA_P4_MASK should be MEM_AREA_P4_BASE
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: bug

#266 Implement POSIX clock_gettime() and friends
  doc/CHANGELOG
  include/kos/time.h
  kernel/libc/posix/Makefile
  kernel/libc/posix/clock_gettime.c
Labels: enhancement

#270 Removing NULL check warning from posix_memalign
  kernel/libc/posix/posix_memalign.c
Labels: cleanup

#272 `dc-chain`: MinGW: Adding Win32 patch for GDB 10.2
  utils/dc-chain/patches/i686-pc-mingw32/gdb-10.2.diff
Labels: toolchain

#212 Controller refactor, documentation, capability queries
  doc/CHANGELOG
  doc/Doxyfile
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/include/dc/maple.h
  kernel/arch/dreamcast/include/dc/maple/controller.h
Labels: enhancement, documentation

#207 VMU driver support for date/time and buttons + documentation update
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/biosfont.h
  kernel/arch/dreamcast/include/dc/maple/vmu.h
Labels: enhancement, documentation
