Repository KallistiOS/KallistiOS, pull requests merged in 2023-10, with the labels that each got.

#318 la_init(): early exit if LAN adapter not detected
  kernel/arch/dreamcast/hardware/network/lan_adapter.c
Labels: cleanup

#322 Enforced matrix alignment, matrix ASM cleanup
  kernel/arch/dreamcast/include/dc/matrix.h
  kernel/arch/dreamcast/include/dc/vec3f.h
  kernel/arch/dreamcast/include/dc/vector.h
  kernel/arch/dreamcast/math/matrix.s
  kernel/arch/dreamcast/math/matrix3d.c
Labels: documentation, cleanup

#319 Doxygen Cleanup/Centralization for Threading APIs
  doc/Doxyfile
  doc/pages/threading.dox
  include/kos/cond.h
  include/kos/genwait.h
  include/kos/mutex.h
  include/kos/once.h
  include/kos/recursive_lock.h
  include/kos/rwsem.h
  include/kos/sem.h
  include/kos/thread.h
  include/kos/tls.h
  include/pthread.h
  include/threads.h
Labels: documentation

#328 Examples refresh
  examples/dreamcast/basic/threading/compiler_tls/Makefile
  examples/dreamcast/kgl/basic/elements/gl-elements.c
  examples/dreamcast/kgl/basic/zclip_arrays/gl-arrays.c
  examples/dreamcast/kgl/demos/blur/radial_blur.c
  examples/dreamcast/kgl/demos/multitexture-arrays/gl-multitex-arrays.c
  examples/dreamcast/kgl/demos/multitexture-elements/gl-multitex-elements.c
  examples/dreamcast/libdream/cdfs/cdfs.c
  examples/dreamcast/pvr/bumpmap/Makefile
  examples/dreamcast/pvr/cheap_shadow/Makefile
  examples/dreamcast/pvr/modifier_volume/Makefile
  examples/dreamcast/pvr/modifier_volume_tex/Makefile
  examples/dreamcast/pvr/plasma/Makefile
  examples/dreamcast/pvr/pvrmark/Makefile
  examples/dreamcast/pvr/pvrmark_strips/Makefile
  examples/dreamcast/pvr/pvrmark_strips_direct/Makefile
  examples/dreamcast/pvr/yuv_converter/YUV420/Makefile
  examples/dreamcast/pvr/yuv_converter/YUV422/Makefile
  examples/dreamcast/sound/hello-mp3/Makefile
Labels: enhancement, cleanup

#324 Watchdog Timer Driver
  doc/CHANGELOG
  examples/dreamcast/basic/Makefile
  examples/dreamcast/basic/watchdog/Makefile
  examples/dreamcast/basic/watchdog/watchdog.c
  include/kos.h
  kernel/arch/dreamcast/include/arch/timer.h
  kernel/arch/dreamcast/include/arch/wdt.h
  kernel/arch/dreamcast/kernel/Makefile
  kernel/arch/dreamcast/kernel/irq.c
  kernel/arch/dreamcast/kernel/wdt.c
Labels: enhancement

#320 Sq refresh plus speed
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/dc/sq.h
Labels: enhancement, documentation

#327 SH4 cache improvements
  kernel/arch/dreamcast/include/arch/cache.h
  kernel/arch/dreamcast/kernel/cache.s
  kernel/exports.txt
Labels: enhancement

#326 Optimized separating stereo PCM 16-bit for streams
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/include/dc/sound/sound.h
  kernel/arch/dreamcast/include/dc/sound/stream.h
  kernel/arch/dreamcast/sound/Makefile
  kernel/arch/dreamcast/sound/snd_pcm_split.s
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement, update

#329 Garbage-collect network stack
  include/kos/init.h
  kernel/arch/dreamcast/hardware/hardware.c
  kernel/arch/dreamcast/kernel/init.c
  kernel/exports/nmmgr.c
Labels: enhancement, update

#332 Fixed sound streams for unaligned buffers.
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug
