Repository KallistiOS/KallistiOS, pull requests merged in 2023-11, with the labels that each got.

#337 SQ style changes
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/dc/sq.h
Labels: cleanup

#334 Improvements for sound FX and added ADPCM long stream support.
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/spu.c
  kernel/arch/dreamcast/include/dc/sound/aica_comm.h
  kernel/arch/dreamcast/include/dc/sound/sound.h
  kernel/arch/dreamcast/include/dc/sound/stream.h
  kernel/arch/dreamcast/include/dc/spu.h
  kernel/arch/dreamcast/sound/snd_pcm_split.s
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement, update

#343 Add sound effects example
  examples/dreamcast/sound/Makefile
  examples/dreamcast/sound/sfx/Makefile
  examples/dreamcast/sound/sfx/main.c
  examples/dreamcast/sound/sfx/romdisk/beep-1.wav
  examples/dreamcast/sound/sfx/romdisk/beep-2.wav
  examples/dreamcast/sound/sfx/romdisk/beep-3.wav
  examples/dreamcast/sound/sfx/romdisk/beep-4.wav
Labels: enhancement

#341 Rework romdisks
  Makefile.rules
  doc/CHANGELOG
  include/kos/init.h
  kernel/Makefile
  kernel/arch/dreamcast/kernel/init.c
  kernel/romdisk/Makefile
  kernel/romdisk/romdiskbase.c
Labels: enhancement

#344 Added Store Queue locking and define's changes
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/dc/sq.h
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement

#346 Sound streams fixes and improvements.
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement

#321 G2 refresh
  doc/CHANGELOG
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/hardware/Makefile
  kernel/arch/dreamcast/hardware/g2bus.c
  kernel/arch/dreamcast/hardware/g2dma.c
  kernel/arch/dreamcast/hardware/hardware.c
  kernel/arch/dreamcast/hardware/network/broadband_adapter.c
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/spu.c
  kernel/arch/dreamcast/hardware/spudma.c
  kernel/arch/dreamcast/include/dc/dmac.h
  kernel/arch/dreamcast/include/dc/fifo.h
  kernel/arch/dreamcast/include/dc/g2bus.h
  kernel/arch/dreamcast/include/dc/pvr.h
  kernel/arch/dreamcast/include/dc/spu.h
  kernel/arch/dreamcast/include/dc/sq.h
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug, update, documentation, cleanup

#352 Fix accidental double free of stream and cleaning code
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug

#365 Removed INIT_THD_PREEMPT startup warning
  include/kos/thread.h
  kernel/arch/dreamcast/kernel/init.c
Labels: cleanup

#366 Complete description of BIOS syscalls for GD-ROM.
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/arch/dreamcast/include/dc/cdrom.h
Labels: enhancement, update, documentation

#369 Enable C99 printf() Formatters in Toolchain Config Samples
  utils/dc-chain/config/config.mk.10.5.0.sample
  utils/dc-chain/config/config.mk.11.4.0.sample
  utils/dc-chain/config/config.mk.12.3.0.sample
  utils/dc-chain/config/config.mk.9.3.0.sample
  utils/dc-chain/config/config.mk.devel.sample
  utils/dc-chain/config/config.mk.legacy.sample
  utils/dc-chain/config/config.mk.stable.sample
  utils/dc-chain/config/config.mk.winxp-latest.sample
Labels: update

#370 Fix Typo in CMake Toolchain for NAOMI
  utils/cmake/dreamcast.toolchain.cmake
Labels: toolchain

#371 Implement SO_RCVBUF and SO_SNDBUF for setsockopt()
  kernel/net/net_tcp.c
Labels: enhancement

#364 Thread-safe audio fixes
  kernel/arch/dreamcast/sound/snd_mem.c
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement

#333 PVR: Add option to specify additional OPBs for TA overflow
  include/kos/opts.h
  kernel/arch/dreamcast/hardware/pvr/pvr_buffers.c
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/vblank.c
  kernel/arch/dreamcast/include/dc/asic.h
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: enhancement

#315 C++20 Concurrency Test/Example
  examples/dreamcast/cpp/Makefile
  examples/dreamcast/cpp/concurrency/Makefile
  examples/dreamcast/cpp/concurrency/concurrency.cpp
Labels: enhancement

#372 Add <netinet/tcp.h> header
  doc/CHANGELOG
  include/netinet/in.h
  include/netinet/tcp.h
  kernel/net/net_tcp.c
Labels: enhancement

#373 Add <netinet/udp.h> and <netinet/udplite.h> headers
  doc/CHANGELOG
  include/netinet/in.h
  include/netinet/udp.h
  include/netinet/udplite.h
  kernel/net/net_udp.c
Labels: enhancement, cleanup

#376 `elf2bin`: adding script to the `utils` directory
  utils/elf2bin/elf2bin
Labels: enhancement

#377 Fixed GD-ROM init for BIOS mod without CD inserted.
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/arch/dreamcast/include/dc/cdrom.h
Labels: bug, enhancement, update

#360 Modularizing KOS, my take
  doc/CHANGELOG
  include/kos/cdefs.h
  include/kos/exports.h
  include/kos/fs_romdisk.h
  include/kos/init.h
  include/kos/init_base.h
  include/kos/nmmgr.h
  kernel/arch/dreamcast/hardware/hardware.c
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/hardware/maple/dreameye.c
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/hardware/maple/lightgun.c
  kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c
  kernel/arch/dreamcast/hardware/maple/mouse.c
  kernel/arch/dreamcast/hardware/maple/purupuru.c
  kernel/arch/dreamcast/hardware/maple/sip.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/arch/init_flags.h
  kernel/arch/dreamcast/include/dc/maple.h
  kernel/arch/dreamcast/include/dc/maple/controller.h
  kernel/arch/dreamcast/include/dc/maple/dreameye.h
  kernel/arch/dreamcast/include/dc/maple/keyboard.h
  kernel/arch/dreamcast/include/dc/maple/lightgun.h
  kernel/arch/dreamcast/include/dc/maple/mouse.h
  kernel/arch/dreamcast/include/dc/maple/purupuru.h
  kernel/arch/dreamcast/include/dc/maple/sip.h
  kernel/arch/dreamcast/include/dc/maple/vmu.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/exports/exports.c
  kernel/exports/nmmgr.c
  kernel/fs/fs_romdisk.c
  kernel/libc/koslib/abort.c
  kernel/romdisk/romdiskbase.c
Labels: enhancement, update, documentation, cleanup

#380 Updated main repo and documentation README
  README.md
Labels: documentation

#384 Fixed Thread-Related Doxygen Warnings
  include/kos/thread.h
  include/threads.h
Labels: documentation

#389 Added check disc change status for cdrom_reinit_ex()
  kernel/arch/dreamcast/hardware/cdrom.c
Labels: bug

#387 Utils: Updating `bin2o` and `elf2bin`
  utils/bin2o/bin2o
  utils/elf2bin/elf2bin
Labels: enhancement

#383 Watchdog Timer Documentation Improvements
  kernel/arch/dreamcast/include/arch/rtc.h
  kernel/arch/dreamcast/include/arch/wdt.h
Labels: documentation
