Repository KallistiOS/KallistiOS, pull requests merged in 2023-05, with the labels that each got.

#171 Correct a number of whitespace issue.
  include/kos/nmmgr.h
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/fs/fs_iso9660.c
  kernel/arch/dreamcast/fs/vmufs.c
  kernel/arch/dreamcast/hardware/biosfont.c
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/arch/dreamcast/hardware/maple/dreameye.c
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/hardware/maple/purupuru.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/hardware/modem/mintr.c
  kernel/arch/dreamcast/hardware/network/broadband_adapter.c
  kernel/arch/dreamcast/hardware/pvr/pvr_fog_tables.h
  kernel/arch/dreamcast/hardware/pvr/pvr_mem_core.c
  kernel/arch/dreamcast/hardware/pvr/pvr_mem_core.h
  kernel/arch/dreamcast/hardware/pvr/pvr_prim.c
  kernel/arch/dreamcast/hardware/scif-spi.c
  kernel/arch/dreamcast/hardware/scif.c
  kernel/arch/dreamcast/include/arch/rtc.h
  kernel/arch/dreamcast/include/arch/spinlock.h
  kernel/arch/dreamcast/include/arch/timer.h
  kernel/arch/dreamcast/include/dc/maple.h
  kernel/arch/dreamcast/include/dc/maple/controller.h
  kernel/arch/dreamcast/include/dc/maple/keyboard.h
  kernel/arch/dreamcast/include/dc/maple/mouse.h
  kernel/arch/dreamcast/include/dc/pvr.h
  kernel/arch/dreamcast/include/dc/video.h
  kernel/arch/dreamcast/kernel/cache.s
  kernel/arch/dreamcast/kernel/exec.c
  kernel/arch/dreamcast/kernel/make_banner.sh
  kernel/arch/dreamcast/kernel/mmu.c
  kernel/arch/dreamcast/kernel/rtc.c
  kernel/arch/dreamcast/kernel/timer.c
  kernel/arch/dreamcast/sound/arm/crt0.s
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
  kernel/arch/dreamcast/util/fb_console.c
  kernel/arch/dreamcast/util/fb_console_naomi.c
  kernel/fs/elf.c
  kernel/fs/fs_utils.c
  kernel/libc/koslib/gethostbyname.c
  kernel/libc/koslib/malloc.c
  kernel/libc/koslib/realpath.c
  kernel/net/net_arp.c
  kernel/net/net_core.c
  kernel/thread/rwsem.c
  kernel/thread/thread.c
  kernel/thread/tls.c
Labels: cleanup

#178 Cleanup of asic.c/h
  kernel/arch/dreamcast/hardware/asic.c
  kernel/arch/dreamcast/include/dc/asic.h
Labels: cleanup

#176 Remove Co-Op threading mode
  doc/CHANGELOG
  examples/dreamcast/hello/hello.c
  include/kos/thread.h
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/thread/thread.c
Labels: cleanup

#201 Set Doxygen main page to updated README.md
  README.md
  doc/Doxyfile
Labels: documentation

#193 Update GDB to use _download_type config
  utils/dc-chain/Makefile
  utils/dc-chain/README.md
  utils/dc-chain/config.mk.legacy.sample
  utils/dc-chain/config.mk.stable.sample
  utils/dc-chain/config.mk.testing.sample
  utils/dc-chain/scripts/clean.mk
  utils/dc-chain/scripts/common.sh
  utils/dc-chain/scripts/download.mk
  utils/dc-chain/scripts/gdb.mk
  utils/dc-chain/scripts/host-detect.mk
  utils/dc-chain/scripts/init.mk
  utils/dc-chain/scripts/phony.mk
  utils/dc-chain/scripts/variables.mk
Labels: toolchain

#206 Updated Doxygen for Threading API
  doc/Doxyfile
  include/kos/thread.h
  kernel/thread/thread.c
Labels: documentation

#202 Fixed Objective-C + added C runtime example
  Makefile.rules
  doc/CHANGELOG
  examples/dreamcast/objc/Makefile
  examples/dreamcast/objc/runtime/Makefile
  examples/dreamcast/objc/runtime/runtime.m
  utils/dc-chain/patches/gcc-13.1.0-kos.diff
  utils/dc-chain/patches/gcc-4.7.4-kos.diff
  utils/dc-chain/patches/gcc-9.3.0-kos.diff
Labels: bug, enhancement, toolchain

#214 Added Quzar's VMUBeep as an Example
  examples/dreamcast/vmu/Makefile
  examples/dreamcast/vmu/vmu_beep/Makefile
  examples/dreamcast/vmu/vmu_beep/beep.c
  examples/dreamcast/vmu/vmu_beep/romdisk/axaxax.txf
Labels: enhancement

#219 Improve fipr() function
  doc/CHANGELOG
  kernel/arch/dreamcast/include/dc/fmath_base.h
Labels: enhancement

#218 Move vector.h from addons to core.
  addons/include/kos/bspline.h
  addons/include/kos/vector.h
  kernel/arch/dreamcast/include/dc/matrix.h
  kernel/arch/dreamcast/include/dc/vector.h
Labels: cleanup

#221 Update AUTHORS
  AUTHORS
Labels: update

#222 Added fast math flags and -fno-builtin options to environ.sh.sample
  doc/environ.sh.sample
  environ_base.sh
Labels: enhancement

#223 vmu: Add function vmu_draw_lcd_rotated()
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/maple/vmu.h
  kernel/arch/dreamcast/include/dc/math.h
  kernel/arch/dreamcast/math/Makefile
  kernel/arch/dreamcast/math/math.s
Labels: enhancement
