Repository KallistiOS/KallistiOS, pull requests merged in 2023-06, with the labels that each got.

#226 vmu: Add VMU framebuffer API
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/Makefile
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: enhancement

#228 Added VMU LCD example using virtual framebuffer
  examples/dreamcast/vmu/Makefile
  examples/dreamcast/vmu/vmu_lcd/Makefile
  examples/dreamcast/vmu/vmu_lcd/lcd.c
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: enhancement

#230 Made vmu_fb_present() honor connector_direction
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: enhancement

#225 Fix some warnings
  addons/libkosext2fs/fs_ext2.c
  addons/libkosutils/netcfg.c
  kernel/arch/dreamcast/fs/vmufs.c
  kernel/arch/dreamcast/hardware/flashrom.c
  kernel/exports.txt
  kernel/fs/fs_utils.c
  kernel/libc/koslib/readdir.c
  utils/genexports/genexportstubs.sh
Labels: cleanup

#227 Add Rumble Example
  doc/CHANGELOG
  examples/dreamcast/Makefile
  examples/dreamcast/rumble/Makefile
  examples/dreamcast/rumble/romdisk/axaxax.txf
  examples/dreamcast/rumble/rumble.c
  kernel/arch/dreamcast/hardware/maple/purupuru.c
Labels: enhancement

#204 Various corrections from static analysis
  addons/libkosext2fs/fs_ext2.c
  include/assert.h
  include/kos/fs_romdisk.h
  include/kos/net.h
  include/kos/thread.h
  kernel/arch/dreamcast/fs/fs_vmu.c
  kernel/arch/dreamcast/fs/vmufs.c
  kernel/arch/dreamcast/include/arch/mmu.h
  kernel/arch/dreamcast/kernel/mmu.c
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
  kernel/fs/fs.c
  kernel/fs/fs_pty.c
  kernel/fs/fs_ramdisk.c
  kernel/fs/fs_romdisk.c
  kernel/libc/koslib/assert.c
  kernel/net/net_arp.c
  kernel/net/net_tcp.c
  kernel/net/net_udp.c
  kernel/thread/thread.c
Labels: enhancement, cleanup

#217 Better handle arch that isn't dreamcast
  examples/dreamcast/basic/memtest32/main.c
  examples/dreamcast/cpp/out_of_memory/out_of_memory.cc
  examples/dreamcast/kgl/basic/elements/gl-elements.c
  examples/dreamcast/kgl/basic/zclip_arrays/gl-arrays.c
  examples/dreamcast/network/httpd/simhost.c
  examples/dreamcast/pvr/bumpmap/bump.c
  examples/dreamcast/pvr/modifier_volume_tex/modifier.c
  examples/dreamcast/sd/speedtest/sd-speedtest.c
  examples/dreamcast/sound/hello-opus/opustest.c
  include/kos.h
  include/kos/fs.h
  include/kos/fs_pty.h
  include/kos/fs_ramdisk.h
  include/kos/fs_romdisk.h
  include/kos/fs_socket.h
  include/kos/limits.h
  include/kos/nmmgr.h
  include/kos/thread.h
  include/sys/lock.h
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/fs/fs_iso9660.c
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/include/dc/fs_dcload.h
  kernel/fs/elf.c
  kernel/libc/koslib/inet_ntoa.c
  kernel/libc/koslib/inet_ntop.c
  kernel/libc/newlib/newlib_getentropy.c
  kernel/libc/pthreads/pthread_mutex.c
  kernel/libc/pthreads/pthread_thd.c
  kernel/thread/cond.c
  kernel/thread/sem.c
  utils/dc-chain/patches/newlib-4.3.0.20230120-kos.diff
  utils/dc-chain/scripts/newlib.mk
Labels: enhancement, cleanup

#243 Update older newlib patches to move lock.h, disable syscalls cleanly.
  utils/dc-chain/patches/historical/newlib-4.1.0-kos.diff
  utils/dc-chain/patches/newlib-2.0.0-kos.diff
  utils/dc-chain/patches/newlib-3.3.0-kos.diff
Labels: toolchain

#247 Moved Noreturn_ attribute to front of thrd_exit().
  include/threads.h
Labels: cleanup
