Repository KallistiOS/KallistiOS, pull requests merged in 2023-03, with the labels that each got.

#117 Merge docker files
  utils/dc-chain/docker/Dockerfile
  utils/dc-chain/docker/README.md
  utils/dc-chain/docker/stable/Dockerfile
Labels: toolchain

#112 `dc-chain`: adding support for GCC 12.2.0 for MinGW-w64
  utils/dc-chain/config.mk.legacy.sample
  utils/dc-chain/config.mk.stable.sample
  utils/dc-chain/config.mk.testing.sample
  utils/dc-chain/patches/i686-w64-mingw32/binutils-2.40.diff
  utils/dc-chain/patches/i686-w64-mingw32/gcc-12.2.0.diff
  utils/dc-chain/patches/i686-w64-mingw32/gcc-8.4.0.diff
  utils/dc-chain/scripts/binutils.mk
  utils/dc-chain/scripts/build.mk
  utils/dc-chain/scripts/patch.mk
Labels: toolchain

#109 Implement a new FS driver for /dev/random and /dev/urandom
  examples/dreamcast/Makefile
  examples/dreamcast/random/Makefile
  examples/dreamcast/random/random.c
  examples/dreamcast/random/romdisk/.keepme
  include/kos.h
  include/kos/fs_dev.h
  kernel/arch/dreamcast/fs/Makefile
  kernel/arch/dreamcast/kernel/init.c
  kernel/arch/dreamcast/kernel/initall_hdrs.h
  kernel/fs/Makefile
  kernel/fs/fs_dev.c
  kernel/libc/newlib/Makefile
  kernel/libc/newlib/newlib_getentropy.c
Labels: enhancement

#131 Removed CXX flags: -fno-rtti and -fno-exceptions
  environ_base.sh
Labels: enhancement

#132 Fixed Undefined symbols for modem with -Os builds
  kernel/arch/dreamcast/hardware/modem/modem.c
Labels: bug

#128 Seperate Pass 1 and Pass 2 GCC folders
  utils/dc-chain/scripts/clean.mk
  utils/dc-chain/scripts/gcc-pass1.mk
  utils/dc-chain/scripts/gcc-pass2.mk
Labels: bug, toolchain

#139 Added timer_ns_gettime64() and performance counters
  doc/CHANGELOG
  kernel/arch/dreamcast/include/arch/timer.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/arch/dreamcast/kernel/timer.c
Labels: enhancement

#91 Added CMake Toolchain file + environment variable
  doc/environ.sh.sample
  utils/cmake/dreamcast.cmake
  utils/cmake/dreamcast.toolchain.cmake
Labels: enhancement, toolchain
