Repository KallistiOS/KallistiOS, pull requests merged in 2023-12, with the labels that each got.

#374 Thread Switch copy speed up
  include/kos/thread.h
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/entry.s
  kernel/arch/dreamcast/kernel/irq.c
  kernel/arch/dreamcast/kernel/thdswitch.s
Labels: enhancement, cleanup

#400 Update dc-chain configs to build new GDB 14.1
  utils/dc-chain/config/config.mk.10.5.0.sample
  utils/dc-chain/config/config.mk.11.4.0.sample
  utils/dc-chain/config/config.mk.12.3.0.sample
  utils/dc-chain/config/config.mk.devel.sample
  utils/dc-chain/config/config.mk.stable.sample
  utils/dc-chain/config/config.mk.winxp-latest.sample
Labels: enhancement

#398 Revert "Thread Switch copy speed up"
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/entry.s
  kernel/arch/dreamcast/kernel/irq.c
  kernel/arch/dreamcast/kernel/thdswitch.s
Labels: bug

#403 Changed Doxygen to use $(KOS_BASE) for Navigator Layout Path
  doc/Doxyfile
Labels: bug, documentation

#405 Updated out_of_memory KOS example
  examples/dreamcast/cpp/out_of_memory/out_of_memory.cc
Labels: update

#411 Updated DoxygenLayout.xml for Doxygen v1.9.8
  doc/pages/DoxygenLayout.xml
Labels: documentation

#410 Fix rotocube example
  examples/dreamcast/parallax/rotocube/Makefile
  examples/dreamcast/parallax/rotocube/rotocube.c
Labels: bug, cleanup

#409 Fix bubbles and serpent examples and remove HBlank settings from
  examples/dreamcast/parallax/bubbles/bubbles.c
  examples/dreamcast/parallax/serpent_dma/serpent.c
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
Labels: bug

#399 Fix face culling bug in CPP GL example and GL_INVALID_ENUM
  examples/dreamcast/cpp/gltest/gltest.cpp
Labels: bug

#407 Handle double promotion
  examples/dreamcast/2ndmix/2ndmix.c
  examples/dreamcast/kgl/basic/gl/gltest.c
  examples/dreamcast/kgl/benchmarks/quadmark/quadmark.c
  examples/dreamcast/kgl/benchmarks/trimark/trimark.c
  examples/dreamcast/kgl/benchmarks/tristripmark/tristripmark.c
  examples/dreamcast/kgl/demos/mipmap/gl-mipmap.c
  examples/dreamcast/kgl/demos/specular/input.c
  examples/dreamcast/kgl/demos/specular/specular.c
  examples/dreamcast/kgl/demos/specular/vector.h
  examples/dreamcast/parallax/bubbles/Makefile
  examples/dreamcast/parallax/bubbles/bubbles.c
  examples/dreamcast/parallax/rotocube/rotocube.c
  examples/dreamcast/parallax/serpent_dma/Makefile
  examples/dreamcast/parallax/serpent_dma/perfmeter.c
  examples/dreamcast/parallax/serpent_dma/serpent.c
  examples/dreamcast/parallax/sinus/sinus.c
  examples/dreamcast/png/example.c
  examples/dreamcast/pvr/plasma/plasma.c
  examples/dreamcast/pvr/pvrmark/pvrmark.c
  examples/dreamcast/pvr/pvrmark_strips/pvrmark_strips.c
  examples/dreamcast/pvr/pvrmark_strips_direct/pvrmark_strips_direct.c
  examples/dreamcast/pvr/texture_render/texture_render.c
  examples/dreamcast/pvr/yuv_converter/YUV420/yuv420.c
  examples/dreamcast/pvr/yuv_converter/YUV422/yuv422.c
  examples/dreamcast/sound/ghettoplay-vorbis/gp.h
  examples/dreamcast/tsunami/banner/banner.cpp
  examples/dreamcast/vmu/vmu_lcd/lcd.c
  kernel/arch/dreamcast/hardware/pvr/pvr_fog.c
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/dc/fmath_base.h
Labels: bug, cleanup

#406 Faster IRQ context saving / restore
  doc/CHANGELOG
  include/kos/thread.h
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/entry.s
  kernel/arch/dreamcast/kernel/thdswitch.s
  kernel/thread/thread.c
Labels: enhancement

#345 Timer Cleanup, Precision Enhancement
  doc/CHANGELOG
  examples/dreamcast/cpp/clock/clock.cc
  kernel/arch/dreamcast/include/arch/timer.h
  kernel/arch/dreamcast/kernel/timer.c
  kernel/libc/c11/timespec_get.c
  kernel/libc/newlib/newlib_gettimeofday.c
  kernel/libc/posix/clock_gettime.c
Labels: bug, enhancement, update, documentation, cleanup

#417 Update memory.h with MMU and UBC registers
  kernel/arch/dreamcast/include/arch/memory.h
  kernel/arch/dreamcast/include/dc/ubc.h
  kernel/arch/dreamcast/kernel/mmu.c
Labels: documentation, cleanup

#421 Renamed likely() and unlikely() Macros
  include/kos/cdefs.h
Labels: cleanup

#428 Added and Improved BBA Doxygen Documentation
  kernel/arch/dreamcast/include/dc/net/broadband_adapter.h
Labels: documentation

#423 Increased Resolution of C's clock() to Microseconds
  doc/CHANGELOG
  include/kos/time.h
  kernel/libc/newlib/newlib_times.c
Labels: enhancement

#429 Added Disclaimer to 800x608 Resolution Example
  examples/dreamcast/libdream/800x608/800x608.c
Labels: update, example

#431 Added Toolchain Option to Enable Newlib's Multibyte/Wide Character Support
  utils/dc-chain/config/config.mk.10.5.0.sample
  utils/dc-chain/config/config.mk.11.4.0.sample
  utils/dc-chain/config/config.mk.12.3.0.sample
  utils/dc-chain/config/config.mk.9.3.0.sample
  utils/dc-chain/config/config.mk.devel.sample
  utils/dc-chain/config/config.mk.legacy.sample
  utils/dc-chain/config/config.mk.stable.sample
  utils/dc-chain/config/config.mk.winxp-latest.sample
  utils/dc-chain/scripts/init.mk
Labels: toolchain

#432 Fix dc-chain host-detect include order
  utils/dc-chain/Makefile
  utils/dc-chain/scripts/init.mk
  utils/dc-chain/scripts/utils.mk
Labels: toolchain

#440 Fixed INIT_MALLOCSTATS KOS init flag
  kernel/libc/koslib/malloc.c
Labels: bug

#439 Disabling Watchdog Timer on KOS exit and init
  examples/dreamcast/basic/watchdog/watchdog.c
  examples/dreamcast/cpp/concurrency/concurrency.cpp
  kernel/arch/dreamcast/include/arch/wdt.h
  kernel/arch/dreamcast/kernel/init.c
Labels: update, example

#430 kthread Barrier Example/Test
  examples/dreamcast/basic/threading/Makefile
  examples/dreamcast/basic/threading/barrier/Makefile
  examples/dreamcast/basic/threading/barrier/barrier.c
Labels: example

#442 Remove non-functional 800x608 mode
  examples/dreamcast/libdream/800x608/800x608.c
  examples/dreamcast/libdream/800x608/Makefile
  examples/dreamcast/libdream/Makefile
  examples/dreamcast/libdream/README
  kernel/arch/dreamcast/hardware/video.c
  kernel/arch/dreamcast/include/dc/video.h
Labels: cleanup

#425 Separate Performance Counter Driver
  doc/CHANGELOG
  include/kos.h
  kernel/arch/dreamcast/include/arch/timer.h
  kernel/arch/dreamcast/include/dc/perfctr.h
  kernel/arch/dreamcast/kernel/Makefile
  kernel/arch/dreamcast/kernel/init.c
  kernel/arch/dreamcast/kernel/perfctr.c
  kernel/arch/dreamcast/kernel/timer.c
Labels: enhancement, documentation, cleanup

#385 Fixes and improvements for Store Queues, Sound and PVR.
  examples/dreamcast/parallax/bubbles/bubbles.c
  examples/dreamcast/pvr/pvrmark_strips_direct/pvrmark_strips_direct.c
  examples/dreamcast/pvr/yuv_converter/YUV420/yuv420.c
  examples/dreamcast/pvr/yuv_converter/YUV422/yuv422.c
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
  kernel/arch/dreamcast/hardware/pvr/pvr_texture.c
  kernel/arch/dreamcast/hardware/spu.c
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/arch/cache.h
  kernel/arch/dreamcast/include/dc/pvr.h
  kernel/arch/dreamcast/include/dc/sound/sfxmgr.h
  kernel/arch/dreamcast/include/dc/sound/sound.h
  kernel/arch/dreamcast/include/dc/spu.h
  kernel/arch/dreamcast/include/dc/sq.h
  kernel/arch/dreamcast/sound/snd_iface.c
  kernel/arch/dreamcast/sound/snd_pcm_split.s
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug, enhancement

#436 Adding examples for `mruby` KallistiOS Port
  examples/dreamcast/mruby/Makefile
  examples/dreamcast/mruby/dreampresent/.gitignore
  examples/dreamcast/mruby/dreampresent/LICENSE
  examples/dreamcast/mruby/dreampresent/Makefile
  examples/dreamcast/mruby/dreampresent/README.md
  examples/dreamcast/mruby/dreampresent/dc_kos_rb.rb
  examples/dreamcast/mruby/dreampresent/dckos.c
  examples/dreamcast/mruby/dreampresent/dckos.h
  examples/dreamcast/mruby/dreampresent/dreampresent.rb
  examples/dreamcast/mruby/dreampresent/main.c
  examples/dreamcast/mruby/dreampresent/page_data.rb
  examples/dreamcast/mruby/dreampresent/presentation.rb
  examples/dreamcast/mruby/dreampresent/romdisk/DCSerialConnector.png
  examples/dreamcast/mruby/dreampresent/romdisk/DCToSerial.png
  examples/dreamcast/mruby/dreampresent/romdisk/bg_dark.png
  examples/dreamcast/mruby/dreampresent/romdisk/content.dreampresent
  examples/dreamcast/mruby/dreampresent/romdisk/dreamcast_photo.png
  examples/dreamcast/mruby/dreampresent/romdisk/emulator_console.png
  examples/dreamcast/mruby/dreampresent/romdisk/mruby_logo_32x35.png
  examples/dreamcast/mruby/dreampresent/romdisk/soldered_connector.png
  examples/dreamcast/mruby/dreampresent/romdisk/swirl_blue_32x28.png
  examples/dreamcast/mruby/dreampresent/romdisk/yuji_avatar.png
  examples/dreamcast/mruby/dreampresent/rsrc/mruby.gif
  examples/dreamcast/mruby/dreampresent/rsrc/mruby.mr
  examples/dreamcast/mruby/dreampresent/start.rb
  examples/dreamcast/mruby/mrbtris/.gitignore
  examples/dreamcast/mruby/mrbtris/LICENSE
  examples/dreamcast/mruby/mrbtris/Makefile
  examples/dreamcast/mruby/mrbtris/README.md
  examples/dreamcast/mruby/mrbtris/block_shapes.rb
  examples/dreamcast/mruby/mrbtris/dckos.c
  examples/dreamcast/mruby/mrbtris/dckos.h
  examples/dreamcast/mruby/mrbtris/main.c
  examples/dreamcast/mruby/mrbtris/mrbtris.rb
  examples/dreamcast/mruby/mrbtris/romdisk/.keep
  examples/dreamcast/mruby/mrbtris/start.rb
Labels: example

#435 Add some gldc examples
  examples/dreamcast/gldc/basic/Makefile
  examples/dreamcast/gldc/basic/gl/Makefile
  examples/dreamcast/gldc/basic/gl/gltest.c
  examples/dreamcast/gldc/basic/gl/pvr-texture.c
  examples/dreamcast/gldc/basic/gl/romdisk/glass.pvr
  examples/dreamcast/gldc/nehe/Makefile
  examples/dreamcast/gldc/nehe/nehe06/Makefile
  examples/dreamcast/gldc/nehe/nehe06/nehe06.c
  examples/dreamcast/gldc/nehe/nehe06/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe06/romdisk/glass.pvr
  examples/dreamcast/gldc/nehe/nehe08/Makefile
  examples/dreamcast/gldc/nehe/nehe08/nehe08.c
  examples/dreamcast/gldc/nehe/nehe08/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe08/romdisk/glass.pvr
  examples/dreamcast/gldc/nehe/nehe09/Makefile
  examples/dreamcast/gldc/nehe/nehe09/nehe09.c
  examples/dreamcast/gldc/nehe/nehe09/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe09/romdisk/star.pvr
  examples/dreamcast/gldc/nehe/nehe16/Makefile
  examples/dreamcast/gldc/nehe/nehe16/nehe16.c
  examples/dreamcast/gldc/nehe/nehe16/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe16/romdisk/glass.pvr
Labels: enhancement, example
