Repository KallistiOS/KallistiOS, pull requests merged in 2023-04, with the labels that each got.

#144 Update Doxyfile version and eliminate all doxygen warnings
  addons/include/ppp/ppp.h
  doc/Doxyfile
  include/kos/fs.h
  include/kos/fs_dev.h
  include/kos/mutex.h
  include/sys/socket.h
  include/sys/uio.h
  kernel/arch/dreamcast/include/dc/asic.h
  kernel/arch/dreamcast/include/dc/maple/controller.h
  kernel/arch/dreamcast/include/dc/maple/keyboard.h
  kernel/arch/dreamcast/include/dc/minifont.h
  kernel/arch/dreamcast/include/dc/sound/stream.h
Labels: documentation

#135 Removed all Compiler Warnings when Building KOS
  addons/libkosfat/directory.c
  addons/libkosfat/fs_fat.c
  addons/libnavi/navi_flash.c
  addons/libnavi/navi_ide.c
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/scif.c
  kernel/arch/dreamcast/kernel/mmu.c
  kernel/arch/dreamcast/sound/snd_stream.c
  kernel/fs/fs.c
  kernel/libc/c11/thrd_create.c
  kernel/libc/koslib/realpath.c
  kernel/net/net_icmp6.c
  kernel/net/net_ipv6.c
  kernel/net/net_udp.c
Labels: enhancement

#110 Fixes and improvements for G1 ATA devices.
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/g1ata.c
  kernel/arch/dreamcast/include/dc/g1ata.h
Labels: enhancement

#134 Link-Time Optimizations (LTO)
  doc/CHANGELOG
  doc/environ.sh.sample
  environ_base.sh
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/biosfont.c
  kernel/arch/dreamcast/include/arch/mmu.h
  kernel/arch/dreamcast/include/dc/spu.h
  kernel/exports.txt
  kernel/libc/koslib/byteorder.c
  utils/genexports/genexports.sh
  utils/genexports/genexportstubs.sh
Labels: enhancement

#122 Properly call newlib's exit to cleanup
  doc/CHANGELOG
  examples/dreamcast/parallax/font/font.c
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/libc/koslib/Makefile
  kernel/libc/koslib/atexit.c
  kernel/libc/newlib/newlib_exit.c
Labels: bug

#154 Add GCC 8.5.0 support for ARM toolchain, bump testing config to GCC 8.5.0 for ARM
  utils/dc-chain/README.md
  utils/dc-chain/config.mk.testing.sample
  utils/dc-chain/patches/arm-Darwin/gcc-8.5.0-kos.diff
  utils/dc-chain/patches/i686-w64-mingw32/gcc-8.5.0.diff
Labels: update, toolchain

#158 Fixed tsnunami font example with GCC12 LTO
  examples/dreamcast/tsunami/font/Makefile
Labels: bug

#159 Fixed building with GCC-4.7.4 after LTO changes
  examples/dreamcast/basic/stackprotector/Makefile
  utils/genexports/genexports.sh
Labels: bug, toolchain

#160 Update copyright notice in GCC and Newlib patches
  utils/dc-chain/patches/gcc-12.2.0-kos.diff
  utils/dc-chain/patches/gcc-4.7.4-kos.diff
  utils/dc-chain/patches/gcc-9.3.0-kos.diff
  utils/dc-chain/patches/historical/gcc-4.4.0-kos.diff
  utils/dc-chain/patches/historical/gcc-4.4.4-kos.diff
  utils/dc-chain/patches/historical/gcc-4.5.2-kos.diff
  utils/dc-chain/patches/historical/gcc-4.7.0-kos.diff
  utils/dc-chain/patches/historical/gcc-4.7.3-kos.diff
  utils/dc-chain/patches/historical/gcc-4.8.1-kos.diff
  utils/dc-chain/patches/historical/gcc-4.8.2-kos.diff
  utils/dc-chain/patches/historical/gcc-9.2.0-kos.diff
  utils/dc-chain/patches/historical/newlib-1.18.0-kos.diff
  utils/dc-chain/patches/historical/newlib-1.19.0-kos.diff
  utils/dc-chain/patches/historical/newlib-1.20.0-kos.diff
  utils/dc-chain/patches/newlib-2.0.0-kos.diff
  utils/dc-chain/patches/newlib-3.3.0-kos.diff
  utils/dc-chain/patches/newlib-4.1.0-kos.diff
  utils/dc-chain/patches/newlib-4.3.0.20230120-kos.diff
Labels: update

#166 Added toolchain support for additional Newlib config options
  utils/dc-chain/config.mk.legacy.sample
  utils/dc-chain/config.mk.stable.sample
  utils/dc-chain/config.mk.testing.sample
  utils/dc-chain/scripts/init.mk
  utils/dc-chain/scripts/newlib.mk
Labels: enhancement, toolchain

#161 Fixed hanging libdream video mode example
  examples/dreamcast/libdream/320x240/320x240.c
  examples/dreamcast/libdream/640x480/640x480.c
  examples/dreamcast/libdream/800x608/800x608.c
Labels: bug

#153 Add support for GCC 13.1.0, bump 'testing' config to GCC 13.1.0
  utils/dc-chain/README.md
  utils/dc-chain/config.mk.testing.sample
  utils/dc-chain/patches/arm-Darwin/gcc-13.1.0-kos.diff
  utils/dc-chain/patches/gcc-13.1.0-kos.diff
  utils/dc-chain/patches/historical/gcc-12.2.0-kos.diff
Labels: update, toolchain

#167 RTC cleanup, documentation, setting date/time
  doc/CHANGELOG
  kernel/arch/dreamcast/include/arch/rtc.h
  kernel/arch/dreamcast/kernel/rtc.c
Labels: enhancement, documentation, cleanup

#155 Add ability to specify git repos for dc-chain sources
  utils/dc-chain/README.md
  utils/dc-chain/cleanup.sh
  utils/dc-chain/config.mk.legacy.sample
  utils/dc-chain/config.mk.stable.sample
  utils/dc-chain/config.mk.testing.sample
  utils/dc-chain/download.sh
  utils/dc-chain/scripts/common.sh
  utils/dc-chain/unpack.sh
Labels: enhancement, toolchain

#150 Cleanup of register access in video.c
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/video.c
  kernel/arch/dreamcast/include/dc/pvr.h
  kernel/arch/dreamcast/include/dc/video.h
  kernel/arch/dreamcast/util/fb_console.c
  kernel/arch/dreamcast/util/fb_console_naomi.c
Labels: documentation, cleanup

#40 Controller Attach/Detach Callbacks
  kernel/arch/dreamcast/hardware/maple/maple_driver.c
  kernel/arch/dreamcast/include/dc/maple.h
Labels: enhancement

#169 Fixed missing header from rtc.c
  kernel/arch/dreamcast/kernel/rtc.c
Labels: bug

#170 Add exit code as argument to dcload exit syscall
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/arch/dreamcast/kernel/startup.s
  utils/dc-chain/patches/gcc-13.1.0-kos.diff
  utils/dc-chain/patches/gcc-4.7.4-kos.diff
  utils/dc-chain/patches/gcc-9.3.0-kos.diff
Labels: enhancement
