Repository KallistiOS/KallistiOS, pull requests merged in 2024-11, with the labels that each got.

#833 Fix G2 DMA race conditions.
  kernel/arch/dreamcast/hardware/g2dma.c
Labels: bug, audio, drivers

#843 Fix versioning macros
  include/kos/version.h
Labels: bug

#844 Fix versioning
  include/kos/version.h
Labels: bug

#845 Bump patch to 1
  include/kos/version.h
Labels: update

#839 Add new regfield.h header, and clean up PVR code
  include/kos.h
  include/kos/regfield.h
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_prim.c
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: cleanup, video, drivers

#830 Gracefully return 0 for ARM/PVR available memory when called before initialization
  kernel/arch/dreamcast/hardware/pvr/pvr_mem.c
  kernel/arch/dreamcast/sound/snd_mem.c
Labels: enhancement, video, audio, drivers

#819 Loadable library recovery and example
  .gitignore
  Makefile.rules
  environ_base.sh
  examples/dreamcast/library/Makefile
  examples/dreamcast/library/exports.txt
  examples/dreamcast/library/library-test.c
  examples/dreamcast/library/loadable-dependence/Makefile
  examples/dreamcast/library/loadable-dependence/exports.txt
  examples/dreamcast/library/loadable-dependence/library-dependence.c
  examples/dreamcast/library/loadable-dependence/library-dependence.h
  examples/dreamcast/library/loadable-dependent/Makefile
  examples/dreamcast/library/loadable-dependent/library-dependent.c
  include/kos/exports.h
  include/kos/library.h
  kernel/exports/exports.c
  kernel/exports/library.c
  kernel/fs/elf.c
  loadable/Makefile.prefab
  loadable/shlelf_dc.xr
Labels: example, kernel
