Repository KallistiOS/KallistiOS, pull requests merged in 2024-02, with the labels that each got.

#480 Quick cleanup for 2D_tex_quad example in GLdc
  examples/dreamcast/gldc/2D_tex_quad/Makefile
  examples/dreamcast/gldc/2D_tex_quad/main.cpp
Labels: cleanup

#477 Bump binutils to 2.42 for dc-chain dev configurations
  utils/dc-chain/config/config.mk.13.2.1-dev.sample
  utils/dc-chain/config/config.mk.14.0.1-dev.sample
Labels: update, toolchain

#478 Allow for --enable-host-shared GCC option in dc-chain configs
  utils/dc-chain/scripts/init.mk
Labels: enhancement, toolchain

#481 Add parens to macros for usage safety
  examples/dreamcast/gldc/basic/gl/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe06/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe08/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe09/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe16/pvr-texture.c
  examples/dreamcast/mruby/dreampresent/dckos.c
  examples/dreamcast/mruby/mrbtris/dckos.c
  examples/dreamcast/pvr/bumpmap/bump.c
  examples/dreamcast/pvr/cheap_shadow/shadow.c
  kernel/arch/dreamcast/hardware/asic.c
  kernel/arch/dreamcast/hardware/g1ata.c
  kernel/arch/dreamcast/hardware/pvr/pvr_buffers.c
  kernel/arch/dreamcast/hardware/sd.c
  kernel/arch/dreamcast/hardware/ubc.c
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/wdt.c
  kernel/net/net_tcp.c
Labels: cleanup

#278 BBA Driver Cleanup
  kernel/arch/dreamcast/hardware/network/broadband_adapter.c
  kernel/arch/dreamcast/include/dc/net/broadband_adapter.h
Labels: documentation, cleanup

#484 Fix cmake function kos_add_romdisk not getting KOS_BASE from ENV
  utils/cmake/dreamcast.cmake
Labels: bug, toolchain

#485 Dockerfile: add alternate github url
  utils/dc-chain/docker/Dockerfile
Labels: enhancement
