Repository KallistiOS/KallistiOS, pull requests merged in 2024-03, with the labels that each got.

#495 Added declarations for clock_xxx() POSIX API
  include/kos/time.h
  include/sys/_pthread.h
Labels: bug

#393 Threaded ASIC IRQ handlers
  kernel/arch/dreamcast/fs/fs_iso9660.c
  kernel/arch/dreamcast/hardware/asic.c
  kernel/arch/dreamcast/hardware/g1ata.c
  kernel/arch/dreamcast/hardware/g2dma.c
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/hardware/maple/dreameye.c
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c
  kernel/arch/dreamcast/hardware/maple/maple_irq.c
  kernel/arch/dreamcast/hardware/maple/mouse.c
  kernel/arch/dreamcast/hardware/maple/purupuru.c
  kernel/arch/dreamcast/hardware/maple/sip.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/hardware/modem/mintr.c
  kernel/arch/dreamcast/hardware/network/broadband_adapter.c
  kernel/arch/dreamcast/hardware/network/lan_adapter.c
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/scif.c
  kernel/arch/dreamcast/hardware/ubc.c
  kernel/arch/dreamcast/hardware/vblank.c
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/include/dc/asic.h
  kernel/arch/dreamcast/include/dc/maple.h
  kernel/arch/dreamcast/include/dc/vblank.h
  kernel/arch/dreamcast/kernel/gdb_stub.c
  kernel/arch/dreamcast/kernel/irq.c
  kernel/arch/dreamcast/kernel/mmu.c
  kernel/arch/dreamcast/kernel/timer.c
  kernel/arch/dreamcast/kernel/wdt.c
Labels: enhancement

#496 Adding KOS_PORTS dir as sysroot for cmake to find libraries
  utils/cmake/dreamcast.toolchain.cmake
Labels: enhancement

#497 dc-chain: Disable GCC documentation
  utils/dc-chain/scripts/gcc-pass1.mk
  utils/dc-chain/scripts/gcc-pass2.mk
Labels: toolchain

#499 Avoid flexible array member in struct dirent
  include/sys/dirent.h
Labels: build failure
