Repository KallistiOS/KallistiOS, pull requests merged in 2024-07, with the labels that each got.

#565 Added Versioning to KOS
  doc/CHANGELOG
  doc/Doxyfile
  environ_base.sh
  include/kos.h
  include/kos/version.h
  kernel/Makefile
  kernel/arch/dreamcast/kernel/make_banner.sh
  kernel/version.c
  utils/version/version.sh
Labels: enhancement, update

#646 /rd . & .. are directories
  kernel/fs/fs_romdisk.c
Labels: bug

#645 /dev rewinddir on close
  kernel/fs/fs_dev.c
Labels: bug

#636 Fix pty
  examples/dreamcast/Makefile
  examples/dreamcast/filesystem/Makefile
  examples/dreamcast/filesystem/pty/Makefile
  examples/dreamcast/filesystem/pty/pty.c
  include/sys/ioctl.h
  include/sys/termios.h
  kernel/fs/fs.c
  kernel/fs/fs_pty.c
  kernel/libc/koslib/Makefile
  kernel/libc/koslib/dbglog.c
  kernel/libc/koslib/dup.c
  kernel/libc/koslib/dup2.c
  kernel/libc/koslib/pipe.c
  kernel/libc/newlib/Makefile
  kernel/libc/newlib/newlib_isatty.c
  kernel/libc/newlib/newlib_tcgetattr.c
Labels: bug, update, example

#650 Fixed vmu_beep example to gracefully exit
  examples/dreamcast/vmu/vmu_beep/beep.c
Labels: bug, enhancement, example

#644 Added Reentrant Mutex Example
  examples/dreamcast/basic/threading/Makefile
  examples/dreamcast/basic/threading/reentrant_mutex/Makefile
  examples/dreamcast/basic/threading/reentrant_mutex/reentrant_mutex.c
Labels: example, kernel

#608 Threaded Controller Callbacks v2
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/include/dc/maple/controller.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/thread/thread.c
  kernel/thread/worker.c
Labels: bug, enhancement, update

#655 Replace redefined regs with dmac.h definitions
  kernel/arch/dreamcast/kernel/init.c
Labels: cleanup

#657 Fix pty compile errors and warnings
  examples/dreamcast/filesystem/pty/pty.c
Labels: bug, example

#652 CDFS: Set errno on errors
  kernel/arch/dreamcast/fs/fs_iso9660.c
Labels: bug, filesystem

#660 Fix example freezes/assertions
  kernel/arch/dreamcast/kernel/init.c
  kernel/fs/fs.c
  kernel/fs/fs_pty.c
Labels: bug, example

#664 cache: Fix ranges of i/d cache flush/inval
  kernel/arch/dreamcast/kernel/cache.s
Labels: bug, drivers

#667 Fix PNG example
  examples/dreamcast/png/example.c
Labels: bug, example

#672 Update profiles using GDB 14.2 to the latest GDB 15.1
  utils/dc-chain/profiles/profile.10.5.0.mk
  utils/dc-chain/profiles/profile.11.4.0.mk
  utils/dc-chain/profiles/profile.12.4.0.mk
  utils/dc-chain/profiles/profile.13.3.0.mk
  utils/dc-chain/profiles/profile.13.3.1-dev.mk
  utils/dc-chain/profiles/profile.14.1.0.mk
  utils/dc-chain/profiles/profile.14.1.1-dev.mk
  utils/dc-chain/profiles/profile.15.0.0-dev.mk
  utils/dc-chain/profiles/profile.9.5.0-winxp.mk
  utils/dc-chain/profiles/profile.gccrs-dev.mk
  utils/dc-chain/profiles/profile.rustc-dev.mk
  utils/dc-chain/profiles/profile.stable.mk
Labels: update, toolchain

#631 Avoid returning error code when examples are too old for toolchain version
  Makefile.rules
  examples/dreamcast/basic/breaking/Makefile
  examples/dreamcast/basic/fpu/exc/Makefile
  examples/dreamcast/basic/stackprotector/Makefile
  examples/dreamcast/cpp/concurrency/Makefile
Labels: build issues, build system

#674 Ensure thd_current does not get set to null
  kernel/thread/genwait.c
  kernel/thread/thread.c
Labels: bug, kernel

#668 Update BBA driver
  kernel/arch/dreamcast/hardware/network/broadband_adapter.c
Labels: update, networking

#677 CMake: Support romdisks in C++ projects
  utils/bin2c/bin2c.c
  utils/cmake/dreamcast.cmake
Labels: enhancement, build system

#687 Fix ramdisk_find
  kernel/fs/fs_ramdisk.c
Labels: bug, filesystem

#663 Fixed GCC9+10 Build Failures: pthread_atfork()
  include/pthread.h
  kernel/libc/pthreads/pthread_thd.c
Labels: build issues

#658 Added utime h POSIX header file
  include/utime.h
Labels: build issues, newlib

#688 Replace duplicated define for the size of the PVR RAM
  kernel/arch/dreamcast/hardware/video.c
Labels: cleanup

#685 Update minimum macOS version for toolchain build
  utils/dc-chain/scripts/init.mk
Labels: toolchain, build issues
