Repository KallistiOS/KallistiOS, pull requests merged in 2024-08, with the labels that each got.

#689 Upgrade to GCC 14.2.0
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/README.md
  utils/dc-chain/patches/gcc-14.2.0-kos.diff
  utils/dc-chain/patches/gcc-14.2.1-kos.diff
  utils/dc-chain/profiles/profile.14.2.0.mk
  utils/dc-chain/profiles/profile.14.2.1-dev.mk
Labels: update, toolchain

#691 Added declaration for nanosleep() to time.h.
  include/kos/time.h
Labels: bug, build issues

#695 dc-chain: Updates to profiles and patches
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/README.md
  utils/dc-chain/patches/gcc-11.5.0-kos.diff
  utils/dc-chain/patches/gcc-15.0.0-kos.diff
  utils/dc-chain/profiles/profile.10.5.0.mk
  utils/dc-chain/profiles/profile.11.5.0.mk
  utils/dc-chain/profiles/profile.12.4.0.mk
  utils/dc-chain/profiles/profile.13.3.0.mk
  utils/dc-chain/profiles/profile.13.3.1-dev.mk
  utils/dc-chain/profiles/profile.14.2.0.mk
  utils/dc-chain/profiles/profile.14.2.1-dev.mk
  utils/dc-chain/profiles/profile.15.0.0-dev.mk
  utils/dc-chain/profiles/profile.gccrs-dev.mk
  utils/dc-chain/profiles/profile.rustc-dev.mk
  utils/dc-chain/profiles/profile.stable.mk
Labels: bug, update, toolchain

#678 Manually aligned PVR primitives to 32-bytes
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: enhancement, video

#701 Fix -Wmaybe-uninitialize warning
  examples/dreamcast/vmu/vmu_beep/beep.c
Labels: example, build issues

#700 Remove g1ata mutex use in biosfont
  kernel/arch/dreamcast/hardware/biosfont.c
Labels: drivers

#529 Fix atomics with LTO
  kernel/arch/dreamcast/kernel/init.c
  kernel/thread/thread.c
Labels: enhancement, build issues

#684 Expanded VFS documentation
  include/kos/fs_romdisk.h
Labels: documentation

#716 Small code/documentation cleanup
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/hardware/sq_fast_cpy.s
  kernel/arch/dreamcast/sound/snd_pcm_split.s
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: documentation, cleanup

#699 vmu: Add function vmu_printf()
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/Makefile
  kernel/arch/dreamcast/util/vmu_printf.c
Labels: enhancement, drivers

#703 Make FD_SETSIZE configurable
  doc/environ.sh.sample
  include/kos/fs.h
  include/kos/opts.h
  include/sys/_types.h
  include/sys/select.h
  kernel/fs/fs.c
Labels: enhancement, filesystem

#697 Fix 24-bit / 32-bit video modes
  kernel/arch/dreamcast/hardware/pvr/pvr_buffers.c
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/video.c
Labels: bug, video

#662 Support chained LBA28 DMA transfers in IDE and DMA transfers in FAT
  addons/libkosfat/bpb.c
  addons/libkosfat/bpb.h
  addons/libkosfat/fatfs.c
  kernel/arch/dreamcast/hardware/g1ata.c
Labels: enhancement, drivers

#659 Iso9660: Read CD-ROM sectors using DMA
  kernel/arch/dreamcast/fs/fs_iso9660.c
Labels: enhancement, filesystem

#714 Add an example of how to render lines with the PVR.
  examples/dreamcast/pvr/Makefile
  examples/dreamcast/pvr/pvrline/Makefile
  examples/dreamcast/pvr/pvrline/pvrline.c
Labels: example, video

#715 `LibADX`: Adding an example for ADX playback
  examples/dreamcast/sound/hello-adx/Makefile
  examples/dreamcast/sound/hello-adx/libADXplay.c
  examples/dreamcast/sound/hello-adx/readme.txt
  examples/dreamcast/sound/hello-adx/romdisk/.keepme
Labels: example, audio

#704 `utils`: adding `font2txf`, a tool to make TXF from TrueType/OpenType fonts
  utils/font2txf/.gitignore
  utils/font2txf/CHANGELOG.md
  utils/font2txf/CREDITS
  utils/font2txf/LICENSE
  utils/font2txf/Makefile
  utils/font2txf/README.md
  utils/font2txf/TODO.md
  utils/font2txf/img/arial.png
  utils/font2txf/src/Makefile
  utils/font2txf/src/Makefile.cfg
  utils/font2txf/src/Makefile.hostdetect
  utils/font2txf/src/charset.cpp
  utils/font2txf/src/charset.h
  utils/font2txf/src/global.cpp
  utils/font2txf/src/global.h
  utils/font2txf/src/main.cpp
  utils/font2txf/src/preview.cpp
  utils/font2txf/src/preview.h
  utils/font2txf/src/txfbuild.cpp
  utils/font2txf/src/txfbuild.h
  utils/font2txf/src/txfwrite.cpp
  utils/font2txf/src/txfwrite.h
  utils/font2txf/src/utils.cpp
  utils/font2txf/src/utils.h
  utils/gentexfont/readme.txt
Labels: utilities

#694 Fixed Overflow with Writing PVR BG Plane
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
Labels: bug, video

#661 Added POSIX settimeofday()
  kernel/arch/dreamcast/include/arch/rtc.h
  kernel/arch/dreamcast/kernel/rtc.c
  kernel/libc/posix/Makefile
  kernel/libc/posix/settimeofday.c
Labels: enhancement, newlib

#730 Fix incorrect file handle checks
  examples/dreamcast/libdream/cdfs/cdfs.c
Labels: bug
