Repository KallistiOS/KallistiOS, pull requests merged in 2024-12, with the labels that each got.

#857 Fix wide character support.
  kernel/arch/dreamcast/include/dc/biosfont.h
Labels: bug, drivers

#820 Reverse the order of searching the genwait timeout queue.
  kernel/thread/genwait.c
Labels: help wanted, kernel, optimization

#872 Posixify environ_*.sh files
  environ_base.sh
  environ_dreamcast.sh
Labels: toolchain

#863 dc-chain: Use "which" instead of "command"
  utils/dc-chain/scripts/utils.mk
Labels: bug, toolchain, build system

#856 Update the changelog and relnotes for v2.1.1
  doc/CHANGELOG.md
  doc/RELNOTES.md
Labels: documentation

#864 Add snd_sfx_load functions that take pointers instead of files
  examples/dreamcast/sound/sfxbuf/Makefile
  examples/dreamcast/sound/sfxbuf/main.c
  examples/dreamcast/sound/sfxbuf/romdisk/beep-1.wav
  examples/dreamcast/sound/sfxbuf/romdisk/beep-2.wav
  examples/dreamcast/sound/sfxbuf/romdisk/beep-3.wav
  examples/dreamcast/sound/sfxbuf/romdisk/beep-4.wav
  kernel/arch/dreamcast/include/dc/sound/sfxmgr.h
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
Labels: enhancement, audio, drivers

#818 Ensure the name manager selects the best match on lookup.
  kernel/exports/nmmgr.c
Labels: bug, kernel, filesystem

#861 Fix and improve CPU cache management for devices on G1 bus.
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/arch/dreamcast/hardware/g1ata.c
  kernel/arch/dreamcast/include/dc/cdrom.h
  kernel/arch/dreamcast/include/dc/g1ata.h
Labels: drivers
