Repository KallistiOS/KallistiOS, pull requests merged in 2024-09, with the labels that each got.

#731 Update pvrtex/stb_image.h from v2.27 to v2.30 to fix compilation warning
  utils/pvrtex/stb_image.h
Labels: update, build issues, utilities

#719 Remove FD_SETSIZE setting from environ.sh
  doc/environ.sh.sample
  include/kos/opts.h
  kernel/fs/fs.c
Labels: enhancement, build system, filesystem

#733 Fix typos in environ.sh
  doc/environ.sh.sample
Labels: documentation

#734 Refactor sysinfo_icon/id
  kernel/arch/dreamcast/hardware/syscalls.c
  kernel/arch/dreamcast/include/dc/syscalls.h
  kernel/arch/dreamcast/kernel/init.c
Labels: enhancement, drivers

#741 aica: Fix the volume LUT
  kernel/arch/dreamcast/sound/arm/aica.c
  kernel/arch/dreamcast/sound/arm/stream.drv.prebuilt
Labels: bug, audio, drivers

#637 Add IRQ-safe mutex / rwsem functions, and scoped mutexes
  include/kos/mutex.h
  include/kos/rwsem.h
  kernel/arch/dreamcast/fs/fs_dclsocket.c
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/exports/nmmgr.c
  kernel/fs/fs_pty.c
  kernel/fs/fs_ramdisk.c
  kernel/fs/fs_socket.c
  kernel/libc/koslib/poll.c
  kernel/net/net_dhcp.c
  kernel/net/net_ipv4_frag.c
  kernel/net/net_multicast.c
  kernel/net/net_tcp.c
  kernel/net/net_udp.c
  kernel/thread/mutex.c
  kernel/thread/rwsem.c
Labels: enhancement, cleanup, kernel

#718 Add getpeername()
  include/kos/fs_socket.h
  include/sys/socket.h
  kernel/fs/fs_socket.c
  kernel/net/net_tcp.c
  kernel/net/net_udp.c
Labels: enhancement, networking

#751 Modified PVR context compilation to be write-only.
  kernel/arch/dreamcast/hardware/pvr/pvr_prim.c
Labels: enhancement, video, drivers

#748 Updated aica memcpy to copy four bytes at a time instead of one.
  kernel/arch/dreamcast/sound/arm/main.c
  kernel/arch/dreamcast/sound/arm/stream.drv.prebuilt
Labels: enhancement, audio, drivers

#747 Docs update
  README.md
  addons/readme.md
  doc/CHANGELOG
  doc/CHANGELOG.md
  doc/FAQ.md
  doc/LICENSE
  doc/LICENSE.md
  doc/README.md
  doc/RELNOTES.md
  doc/goals.md
  doc/license/LICENSE.BSD
  doc/license/LICENSE.GPL
  doc/license/LICENSE.KOS
  doc/license/LICENSE.LGPL
  doc/modem.txt
  doc/style.md
  examples/dreamcast/readme.md
  utils/readme.md
Labels: update, documentation, cleanup

#750 Updated the version number for KOS 2.1.0.
  include/kos/version.h
Labels: update

#634 Add . & .. to filesystems and filesystem example
  doc/CHANGELOG.md
  examples/dreamcast/filesystem/browse/Makefile
  examples/dreamcast/filesystem/browse/browse.c
  examples/dreamcast/filesystem/browse/browse.h
  examples/dreamcast/filesystem/browse/romdisk/file.txt
  examples/dreamcast/filesystem/browse/romdisk/test/file2.txt
  examples/dreamcast/filesystem/sd/Makefile
  examples/dreamcast/filesystem/sd/ext2fs/Makefile
  examples/dreamcast/filesystem/sd/ext2fs/sd-ext2fs.c
  examples/dreamcast/filesystem/sd/mke2fs/Makefile
  examples/dreamcast/filesystem/sd/mke2fs/Makefile.nonkos
  examples/dreamcast/filesystem/sd/mke2fs/mke2fs.c
  examples/dreamcast/filesystem/sd/speedtest/Makefile
  examples/dreamcast/filesystem/sd/speedtest/sd-speedtest.c
  include/kos/nmmgr.h
  kernel/fs/fs.c
Labels: bug, enhancement, example, filesystem

#732 Added small approval test on binary output from pvrtex
  utils/pvrtex/approvaltest/.gitignore
  utils/pvrtex/approvaltest/Makefile
  utils/pvrtex/approvaltest/crate.png
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt/texture.dt
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_argb4444_-d_-c_64_-m_quality_-r_-R/texture.dt
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_normal_-m/texture.dt
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_pal4bpp_-d_-p_tests_run_preview_png/preview.png
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_pal4bpp_-d_-p_tests_run_preview_png/texture.dt
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_pal4bpp_-d_-p_tests_run_preview_png/texture.dt.pal
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_pal8bpp_-C_64_-d/texture.dt
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-f_pal8bpp_-C_64_-d/texture.dt.pal
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_dt_-s/texture.dt
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_tex/texture.tex
  utils/pvrtex/approvaltest/tests/approved/-i_crate_png_-o_tests_run_texture_vq/texture.vq
Labels: enhancement, utilities

#755 Update/Fix wav2adpcm
  utils/wav2adpcm/wav2adpcm.c
Labels: bug, utilities, audio

#749 utils/pvrtex: fix and improve Makefile
  utils/pvrtex/Makefile
Labels: build issues, utilities

#765 Scoped IRQ disable
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/exports/library.c
  kernel/net/net_dhcp.c
  kernel/net/net_tcp.c
  kernel/net/net_thd.c
  kernel/thread/cond.c
  kernel/thread/genwait.c
  kernel/thread/mutex.c
  kernel/thread/rwsem.c
  kernel/thread/sem.c
  kernel/thread/thread.c
  kernel/thread/worker.c
Labels: enhancement, kernel

#752 Fixed KOS's Makefile.rules: CFLAGS, CXXFLAGS, CPPFLAGS.
  Makefile.rules
Labels: cleanup, build system

#725 PVR API cleanups
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_palette.c
  kernel/arch/dreamcast/hardware/pvr/pvr_prim.c
  kernel/arch/dreamcast/hardware/pvr/pvr_texture.c
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: cleanup, video

#648 Replace realpath() for a better license
  AUTHORS
  doc/CHANGELOG.md
  include/kos/fs.h
  kernel/fs/fs.c
  kernel/fs/fs_utils.c
  kernel/libc/koslib/realpath.c
Labels: update, filesystem

#706 Downsized stack sizes for idle and reaper threads
  kernel/thread/thread.c
Labels: enhancement, kernel

#777 bin2c's Makefile bug
  utils/bin2c/Makefile
Labels: bug, utilities

#771 Clean up usage of `INLINE` in utils
  utils/dcbumpgen/Makefile
  utils/kmgenc/Makefile
  utils/vqenc/Makefile
  utils/vqenc/vq_internal.h
  utils/vqenc/vqenc.c
Labels: cleanup, utilities

#675 Helper functions and examples for modifier volumes and Z clipping
  examples/dreamcast/pvr/modifier_volume_zclip/Makefile
  examples/dreamcast/pvr/modifier_volume_zclip/example.c
  examples/dreamcast/pvr/modifier_volume_zclip/pvr_zclip.c
  examples/dreamcast/pvr/modifier_volume_zclip/pvr_zclip.h
  examples/dreamcast/pvr/modifier_volume_zclip/romdisk/blocks.png
Labels: enhancement, example, video

#707 Cleaned up + optimized pvrmark_strips_direct bench
  examples/dreamcast/pvr/pvrmark_strips_direct/pvrmark_strips_direct.c
Labels: cleanup, example, video

#671 Network speedtest
  examples/dreamcast/network/Makefile
  examples/dreamcast/network/speedtest/Makefile
  examples/dreamcast/network/speedtest/handle_request.c
  examples/dreamcast/network/speedtest/romdisk/index.html
  examples/dreamcast/network/speedtest/server.c
  examples/dreamcast/network/speedtest/speedtest.c
  examples/dreamcast/network/speedtest/speedtest.h
Labels: example, networking
