Repository KallistiOS/KallistiOS, pull requests merged in 2024-01, with the labels that each got.

#444 Fix KGL Nehe26 Example Build Failure
  examples/dreamcast/kgl/nehe/nehe26/nehe26.c
Labels: bug, example

#443 Fixed GLdc Nehe26 Example Build Failure
  examples/dreamcast/gldc/nehe/nehe26/nehe26.c
Labels: bug, example

#448 Fix serpent_dma example
  AUTHORS
  examples/dreamcast/parallax/serpent_dma/serpent.c
Labels: bug, example

#449 Add support for Newlib 4.4.0
  AUTHORS
  kernel/libc/newlib/newlib_getentropy.c
  utils/dc-chain/patches/newlib-4.4.0.20231231-kos.diff
Labels: enhancement, update, toolchain

#455 Changed abort() to call arch_abort()
  kernel/libc/koslib/abort.c
Labels: enhancement

#458 Fixed Romdisks and Added Bin2Object Support to CMake Toolchain
  utils/cmake/dreamcast.cmake
  utils/cmake/dreamcast.toolchain.cmake
Labels: update, toolchain

#460 Add environ variable for SH4 floating point precision configuration
  doc/environ.sh.sample
  environ_dreamcast.sh
Labels: enhancement, toolchain

#459 Hello Example Cleanup and Update
  examples/dreamcast/hello/Makefile
  examples/dreamcast/hello/hello.c
  examples/dreamcast/hello/romdisk/.keepme
Labels: update, example

#454 Fixed Build Issue with -Og for inode.c
  addons/libkosext2fs/inode.c
Labels: build failure

#427 Added CLOCK_PROCESS_CPUTIME_ID + clock_getcpuclockid()
  AUTHORS
  doc/CHANGELOG
  include/kos/time.h
  kernel/libc/posix/clock_gettime.c
Labels: enhancement

#462 Fixed romdisks and bin2o in Cmake toolchain
  utils/cmake/dreamcast.cmake
Labels: bug, toolchain

#464 Added <dc/vmu_fb.h> to <kos.h>
  include/kos.h
Labels: bug

#461 Added Toolchain Config Variable for Disabling NLS.
  utils/dc-chain/config/config.mk.10.5.0.sample
  utils/dc-chain/config/config.mk.11.4.0.sample
  utils/dc-chain/config/config.mk.12.3.0.sample
  utils/dc-chain/config/config.mk.13.2.1-dev.sample
  utils/dc-chain/config/config.mk.14.0.1-dev.sample
  utils/dc-chain/config/config.mk.4.7.4-legacy.sample
  utils/dc-chain/config/config.mk.9.3.0-legacy.sample
  utils/dc-chain/config/config.mk.9.5.0-winxp.sample
  utils/dc-chain/config/config.mk.stable.sample
  utils/dc-chain/doc/CONTRIBUTORS.md
  utils/dc-chain/doc/changelog.txt
  utils/dc-chain/scripts/build.mk
  utils/dc-chain/scripts/init.mk
Labels: toolchain

#468 Added --disable-nls Support to Binutils as Well
  utils/dc-chain/scripts/binutils.mk
  utils/dc-chain/scripts/init.mk
Labels: bug, toolchain

#469 1-20-24 - Fixed depth test issues and added color buffer clear to act…
  examples/dreamcast/gldc/basic/gl/gltest.c
Labels: bug, example

#465 Added Newlines Around main() Console Output
  examples/dreamcast/hello/hello.c
  kernel/arch/dreamcast/kernel/init.c
Labels: enhancement, example

#472 Added doxygen category for assertion handlers
  include/assert.h
Labels: documentation

#453 Implement POSIX scandir() + alphasort() for dirent.h
  doc/CHANGELOG
  include/sys/dirent.h
  kernel/libc/koslib/readdir.c
  kernel/libc/koslib/scandir.c
Labels: enhancement

#419 Refactor Multibuffered video modes
  AUTHORS
  doc/CHANGELOG
  examples/dreamcast/video/Makefile
  examples/dreamcast/video/multibuffer/Makefile
  examples/dreamcast/video/multibuffer/multibuffer.c
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/biosfont.c
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/video.c
  kernel/arch/dreamcast/include/dc/video.h
Labels: enhancement, cleanup

#416 UBC Driver Upgrade
  doc/CHANGELOG
  examples/dreamcast/basic/Makefile
  examples/dreamcast/basic/breaking/Makefile
  examples/dreamcast/basic/breaking/breaking.c
  include/kos/cdefs.h
  include/kos/iovec.h
  kernel/arch/dreamcast/hardware/Makefile
  kernel/arch/dreamcast/hardware/ubc.c
  kernel/arch/dreamcast/include/dc/ubc.h
  kernel/arch/dreamcast/kernel/init.c
Labels: update, documentation, example

#474 Fixed libparallax bubbles and rotocube examples
  examples/dreamcast/parallax/bubbles/bubbles.c
  examples/dreamcast/parallax/rotocube/rotocube.c
Labels: bug, example

#457 Fixed Newlib's getpid() and Implemented kill()
  include/kos/thread.h
  kernel/libc/newlib/newlib_getpid.c
  kernel/libc/newlib/newlib_kill.c
  kernel/libc/posix/clock_gettime.c
Labels: bug, enhancement
