Repository KallistiOS/KallistiOS, pull requests merged in 2024-06, with the labels that each got.

#601 Correct bitmasks in fpu_exc stringify
  examples/dreamcast/basic/fpu/exc/fpu_exc.c
Labels: bug, example

#589 Better error/warning handling in some examples
  examples/dreamcast/2ndmix/2ndmix.c
  examples/dreamcast/basic/mmu/nullptr/nullptr.c
  examples/dreamcast/basic/mmu/pvrmap/pvrmap.c
  examples/dreamcast/basic/stackprotector/stackprotector.c
  examples/dreamcast/dev/devroot/devroot.c
  examples/dreamcast/network/httpd/httpd.c
  examples/dreamcast/parallax/serpent_dma/perfmeter.c
  examples/dreamcast/parallax/serpent_dma/serpent.c
  examples/dreamcast/png/example.c
  examples/dreamcast/rumble/rumble.c
  examples/dreamcast/sound/multi-stream/main.c
  examples/dreamcast/sound/sfx/main.c
  examples/dreamcast/vmu/vmu_beep/beep.c
Labels: bug, cleanup

#604 Avoid infinite loop in mouse example (also, is mouse broken?)
  examples/dreamcast/libdream/mouse/mouse.c
Labels: bug, help wanted, example

#603 Updated OS-Level TLS Example
  examples/dreamcast/basic/threading/tls/tls_test.c
Labels: enhancement, example

#599 Malloc leak and debug fixes
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/hardware/pvr/pvr_mem.c
  kernel/debug/dbgio.c
  kernel/exports/nmmgr.c
  kernel/fs/fs.c
  kernel/fs/fs_ramdisk.c
  kernel/libc/koslib/dbglog.c
  kernel/libc/koslib/malloc.c
  kernel/mm/malloc_debug.c
  kernel/thread/thread.c
  kernel/thread/tls.c
Labels: bug, cleanup

#551 Some cleanups in Maple
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/hardware/maple/dreameye.c
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/hardware/maple/lightgun.c
  kernel/arch/dreamcast/hardware/maple/maple_driver.c
  kernel/arch/dreamcast/hardware/maple/maple_enum.c
  kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c
  kernel/arch/dreamcast/hardware/maple/maple_irq.c
  kernel/arch/dreamcast/hardware/maple/mouse.c
  kernel/arch/dreamcast/hardware/maple/purupuru.c
  kernel/arch/dreamcast/hardware/maple/sip.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/maple.h
  kernel/arch/dreamcast/include/dc/maple/mouse.h
  kernel/arch/dreamcast/include/dc/maple/vmu.h
Labels: enhancement, cleanup

#513 Added support for pthread_condattr_setclock()
  addons/libpthread/pthread-internal.h
  addons/libpthread/pthread_cond_init.c
  addons/libpthread/pthread_cond_timedwait.c
  addons/libpthread/pthread_condattr_getclock.c
  addons/libpthread/pthread_condattr_init.c
  addons/libpthread/pthread_condattr_setclock.c
  addons/libpthread/pthread_mutex_timedlock.c
  addons/libpthread/pthread_rwlock_timedrdlock.c
  addons/libpthread/pthread_rwlock_timedwrlock.c
  doc/CHANGELOG
  include/kos/barrier.h
  include/sys/_pthreadtypes.h
Labels: bug, enhancement

#591 Add Makefile rule to check minimum GCC version
  Makefile.rules
  examples/dreamcast/basic/breaking/Makefile
  examples/dreamcast/basic/fpu/exc/Makefile
  examples/dreamcast/basic/stackprotector/Makefile
  examples/dreamcast/cpp/concurrency/Makefile
Labels: enhancement, update, example, build failure, utilities

#610 Fixed warnings when compiling with builtins
  kernel/libc/koslib/readdir.c
  kernel/libc/newlib/newlib_exit.c
Labels: build issues

#609 Improve environ.sh handling of built-in flag for fast math
  doc/environ.sh.sample
Labels: enhancement

#605 Fixed false failure in once_test on 16MB RAM
  examples/dreamcast/basic/threading/once/once_test.c
Labels: bug, example

#560 Fix KOS + Examples when using LTO without -fno-builtins
  kernel/libc/koslib/assert.c
  kernel/libc/newlib/newlib_exit.c
  kernel/libc/newlib/newlib_malloc.c
Labels: build issues

#612 Fixed broken build.
  kernel/libc/newlib/newlib_exit.c
Labels: build issues

#550 Implemented C23 stdlib features for <time.h>
  doc/CHANGELOG
  include/kos/time.h
  kernel/arch/dreamcast/kernel/rtc.c
  kernel/libc/c11/Makefile
  kernel/libc/c11/timegm.c
  kernel/libc/c11/timespec_get.c
  kernel/libc/posix/clock_gettime.c
Labels: enhancement, update, cleanup

#615 Fix building libstunami examples on GCC9&10
  examples/dreamcast/tsunami/banner/Makefile
  examples/dreamcast/tsunami/font/Makefile
  examples/dreamcast/tsunami/genmenu/Makefile
Labels: example, build issues

#616 Fix cpp/clock example on GCC9&10
  examples/dreamcast/cpp/clock/Makefile
Labels: example, build issues

#620 Fixed a MASSIVE screw-up with enabling OCRAM.
  kernel/arch/dreamcast/kernel/startup.s
Labels: bug

#613 Add DC_TOOLS_BASE env variable for external tools
  doc/environ.sh.sample
  environ_base.sh
  environ_dreamcast.sh
Labels: enhancement, utilities

#622 Thread bugfixes: Stack ownership, Genwait object release upon death
  include/kos/thread.h
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/mm.c
  kernel/thread/thread.c
Labels: bug

#607 Fix texturing and closing opened files
  examples/dreamcast/cpp/gltest/gltest.cpp
  examples/dreamcast/gldc/basic/gl/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe06/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe08/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe09/pvr-texture.c
  examples/dreamcast/gldc/nehe/nehe16/pvr-texture.c
  examples/dreamcast/png/example.c
  examples/dreamcast/video/screenshot/screenshot.c
Labels: bug, example

#624 Some CMake stuff
  utils/cmake/dreamcast.cmake
  utils/cmake/dreamcast.toolchain.cmake
Labels: build system

#643 mutex: Fix mutexes not mutexing
  doc/CHANGELOG
  kernel/thread/mutex.c
Labels: bug, kernel

#642 fs_dcload: Set errno on error in dcload_stat()
  doc/CHANGELOG
  kernel/arch/dreamcast/fs/fs_dcload.c
Labels: bug

#641 Create romdisks with bin2c instead of bin2o
  Makefile.rules
  doc/CHANGELOG
  include/kos/init.h
  kernel/romdisk/romdiskbase.c
  utils/bin2c/bin2c.c
  utils/cmake/dreamcast.cmake
Labels: enhancement, build system

#640 dc-chain: Update 12.x profile to 12.4
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/patches/gcc-12.4.0-kos.diff
  utils/dc-chain/patches/historical/gcc-12.3.0-kos.diff
  utils/dc-chain/profiles/profile.12.4.0.mk
Labels: update, toolchain

#633 Correct raster_melt memory leak
  examples/dreamcast/parallax/raster_melt/raster_melt.c
Labels: bug, example

#630 Clean up after all the allocations done in serpent_dma
  examples/dreamcast/parallax/serpent_dma/perfmeter.c
  examples/dreamcast/parallax/serpent_dma/serpent.c
Labels: bug, example

#611 pthread: Add dummy pthread_atfork() for CMake detection
  kernel/libc/pthreads/pthread_thd.c
Labels: update

#647 /sd directories viewed as files
  addons/libkosfat/fs_fat.c
Labels: bug
