Repository KallistiOS/KallistiOS, pull requests merged in 2024-10, with the labels that each got.

#789 Remove LTO flags from pvrtex
  utils/pvrtex/Makefile
Labels: update, build system

#785 environ_base.sh: Remove `-fno-operator-names` flag
  environ_base.sh
Labels: build issues, build system

#784 Make the Store Queue mutex recursive
  kernel/arch/dreamcast/hardware/sq.c
Labels: bug, enhancement, kernel, drivers

#790 Made macros for HZ and THD stack sizes overridable
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/thread/thread.c
Labels: enhancement, build system

#552 maple: Rework device detection, allocation and status buffers
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/hardware/maple/dreameye.c
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/hardware/maple/maple_driver.c
  kernel/arch/dreamcast/hardware/maple/maple_enum.c
  kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c
  kernel/arch/dreamcast/hardware/maple/maple_irq.c
  kernel/arch/dreamcast/hardware/maple/maple_queue.c
  kernel/arch/dreamcast/hardware/maple/maple_utils.c
  kernel/arch/dreamcast/hardware/maple/mouse.c
  kernel/arch/dreamcast/hardware/maple/sip.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/maple.h
Labels: enhancement, cleanup

#775 Filesystem Stat fixes
  addons/libkosext2fs/fs_ext2.c
  addons/libkosfat/fs_fat.c
  examples/dreamcast/filesystem/browse/browse.c
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/fs/fs_iso9660.c
  kernel/arch/dreamcast/fs/fs_vmu.c
  kernel/exports.txt
  kernel/fs/fs_dev.c
  kernel/fs/fs_null.c
  kernel/fs/fs_pty.c
  kernel/fs/fs_ramdisk.c
  kernel/fs/fs_random.c
  kernel/fs/fs_romdisk.c
  kernel/fs/fs_utils.c
  kernel/libc/koslib/realpath.c
Labels: bug, filesystem

#796 Adjust example for removal of maple_device_t element 'valid'
  examples/dreamcast/rumble/rumble.c
Labels: bug, drivers

#770 Update mat_transform() parameter name and description
  kernel/arch/dreamcast/include/dc/matrix.h
Labels: documentation, math

#573 Speed up building KOS and examples
  Makefile
  Makefile.rules
  addons/Makefile
  examples/Makefile
  examples/dreamcast/Makefile
  examples/dreamcast/basic/Makefile
  examples/dreamcast/basic/fpu/Makefile
  examples/dreamcast/basic/mmu/Makefile
  examples/dreamcast/basic/threading/Makefile
  examples/dreamcast/conio/Makefile
  examples/dreamcast/cpp/Makefile
  examples/dreamcast/dev/Makefile
  examples/dreamcast/dreameye/Makefile
  examples/dreamcast/filesystem/Makefile
  examples/dreamcast/filesystem/sd/Makefile
  examples/dreamcast/g1ata/Makefile
  examples/dreamcast/g1ata/atatest/Makefile
  examples/dreamcast/gldc/Makefile
  examples/dreamcast/gldc/basic/Makefile
  examples/dreamcast/gldc/benchmarks/Makefile
  examples/dreamcast/gldc/nehe/Makefile
  examples/dreamcast/keyboard/Makefile
  examples/dreamcast/kgl/Makefile
  examples/dreamcast/kgl/basic/Makefile
  examples/dreamcast/kgl/benchmarks/Makefile
  examples/dreamcast/kgl/demos/Makefile
  examples/dreamcast/kgl/nehe/Makefile
  examples/dreamcast/libdream/Makefile
  examples/dreamcast/lightgun/Makefile
  examples/dreamcast/lua/Makefile
  examples/dreamcast/modem/Makefile
  examples/dreamcast/modem/basic/Makefile
  examples/dreamcast/modem/ppp/Makefile
  examples/dreamcast/mruby/Makefile
  examples/dreamcast/network/Makefile
  examples/dreamcast/network/basic/Makefile
  examples/dreamcast/network/dns-client/Makefile
  examples/dreamcast/network/httpd/Makefile
  examples/dreamcast/network/isp-settings/Makefile
  examples/dreamcast/network/ntp/Makefile
  examples/dreamcast/network/ping/Makefile
  examples/dreamcast/network/ping6/Makefile
  examples/dreamcast/network/speedtest/Makefile
  examples/dreamcast/network/udpecho6/Makefile
  examples/dreamcast/objc/Makefile
  examples/dreamcast/parallax/Makefile
  examples/dreamcast/pvr/Makefile
  examples/dreamcast/pvr/yuv_converter/Makefile
  examples/dreamcast/sdl/Makefile
  examples/dreamcast/sound/Makefile
  examples/dreamcast/sound/cdda/Makefile
  examples/dreamcast/tsunami/Makefile
  examples/dreamcast/video/Makefile
  examples/dreamcast/vmu/Makefile
  utils/Makefile
Labels: enhancement, example

#791 Fixed pvrtex warnings with Clang18 host compiler
  utils/pvrtex/Makefile
  utils/pvrtex/mem.c
  utils/pvrtex/pvr_texture_encoder.c
Labels: build issues, utilities

#783 thread: Add priority boosting system
  doc/CHANGELOG.md
  include/kos/thread.h
  kernel/thread/mutex.c
  kernel/thread/thread.c
Labels: enhancement, kernel

#673 Don't allow dbgio until it is initted
  kernel/debug/dbgio.c
Labels: bug, kernel

#614 Improve diagnose message
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/irq.c
Labels: enhancement

#795 kernel: Add performance monitor API
  doc/CHANGELOG.md
  kernel/arch/dreamcast/include/dc/perf_monitor.h
  kernel/arch/dreamcast/kernel/Makefile
  kernel/arch/dreamcast/kernel/perf_monitor.c
  utils/ldscripts/shlelf.xc
Labels: utilities

#793 Made builtin font used by vmu_printf() public.
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/vmu_fb.c
  kernel/arch/dreamcast/util/vmu_printf.c
Labels: enhancement

#800 Fix unused parameter warning
  kernel/arch/dreamcast/hardware/maple/maple_irq.c
Labels: build issues, drivers

#801 thread: Improve priority boosting
  kernel/thread/mutex.c
Labels: enhancement, kernel

#802 Add pvr palette related examples
  doc/CHANGELOG.md
  examples/dreamcast/pvr/palette/4bpp/4bpp.c
  examples/dreamcast/pvr/palette/4bpp/Makefile
  examples/dreamcast/pvr/palette/8bpp/8bpp.c
  examples/dreamcast/pvr/palette/8bpp/Makefile
  examples/dreamcast/pvr/palette/wormhole/Makefile
  examples/dreamcast/pvr/palette/wormhole/wormhole.c
  examples/dreamcast/readme.md
Labels: example, video

#759 Add documentation guide for users and maintainers
  doc/DOCGUIDE.md
Labels: enhancement, documentation

#803 Fixed Thread Starvation Issue with Priority Boosting
  kernel/thread/mutex.c
Labels: bug, kernel

#814 Fix dreampresent example
  examples/dreamcast/mruby/dreampresent/page_data.rb
Labels: bug, example

#813 perf_monitor: Improve perf_monitor_print()
  kernel/arch/dreamcast/kernel/perf_monitor.c
Labels: enhancement, utilities

#810 Separate out trap from irq.
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/include/arch/trap.h
  kernel/arch/dreamcast/kernel/gdb_stub.c
  kernel/arch/dreamcast/kernel/irq.c
Labels: enhancement, update, cleanup, kernel

#581 BIOS Font Cleanup, Refactor, and More Ergonomic API
  doc/CHANGELOG.md
  examples/dreamcast/libdream/320x240/320x240.c
  examples/dreamcast/mruby/mrbtris/dckos.c
  examples/dreamcast/sound/multi-stream/main.c
  examples/dreamcast/video/multibuffer/multibuffer.c
  kernel/arch/dreamcast/hardware/biosfont.c
  kernel/arch/dreamcast/include/dc/biosfont.h
Labels: enhancement, documentation, cleanup, example, video

#595 Minor cleanups in FS
  include/sys/dirent.h
  kernel/arch/dreamcast/fs/fs_iso9660.c
  kernel/arch/dreamcast/fs/fs_vmu.c
  kernel/fs/fs.c
  kernel/fs/fs_null.c
  kernel/fs/fs_random.c
  kernel/fs/fs_romdisk.c
Labels: cleanup, filesystem

#815 Refactor and cleanup of IRQ system (Part 2)
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/irq.c
Labels: enhancement, cleanup, kernel, drivers

#762 Sound improvements and fixes
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/g2dma.c
  kernel/arch/dreamcast/hardware/spu.c
  kernel/arch/dreamcast/include/dc/sound/sfxmgr.h
  kernel/arch/dreamcast/include/dc/sound/stream.h
  kernel/arch/dreamcast/include/dc/spu.h
  kernel/arch/dreamcast/sound/snd_pcm_split.s
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement, audio, drivers

#823 The sys/queue `_FOREACH` functions are not safe to free their elements.
  kernel/net/net_dhcp.c
Labels: bug, networking

#821 Set ramdisk's `stat` to return 0 on successful completion.
  kernel/fs/fs_ramdisk.c
Labels: bug, filesystem

#817 [RFC] pvr: Add new function pvr_send_to_ta()
  kernel/arch/dreamcast/hardware/pvr/Makefile
  kernel/arch/dreamcast/hardware/pvr/pvr_send_to_ta.s
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: enhancement

#832 Consistency fix in environ_base.sh
  environ_base.sh
Labels: documentation, cleanup
