Repository KallistiOS/KallistiOS, pull requests merged in 2024-04, with the labels that each got.

#502 change g2_ctx_t->irq_state type from `uint32_t` to `int`
  kernel/arch/dreamcast/include/dc/g2bus.h
Labels: cleanup

#473 Added NDEBUG option to environ.sh.sample
  doc/environ.sh.sample
Labels: enhancement

#509 init: Add KOS_NO_SHUTDOWN flag to disable shutdown
  include/kos/init.h
  kernel/libc/newlib/newlib_exit.c
Labels: enhancement

#517 maple: Fix race between IRQ and threads
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/include/dc/maple/keyboard.h
Labels: bug

#521 Updated Copyright Date for KOS's License
  kernel/arch/dreamcast/kernel/banner.c
Labels: update

#516 init: Add init flags to enable/disable DCLOAD, CDROM
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/fs/fs_dclsocket.c
  kernel/arch/dreamcast/fs/fs_iso9660.c
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/arch/dreamcast/hardware/hardware.c
  kernel/arch/dreamcast/include/arch/init_flags.h
  kernel/arch/dreamcast/include/dc/cdrom.h
  kernel/arch/dreamcast/include/dc/fs_dcload.h
  kernel/arch/dreamcast/include/dc/fs_dclsocket.h
  kernel/arch/dreamcast/include/dc/fs_iso9660.h
  kernel/arch/dreamcast/kernel/init.c
Labels: enhancement

#522 Updated the AUTHORS file to Add 2024 Dates
  AUTHORS
Labels: update, documentation

#511 fs: Remove duplicated fcntl() function
  kernel/fs/fs.c
  kernel/libc/newlib/newlib_fcntl.c
Labels: cleanup, build failure

#501 cmake: Simplify toolchain script
  environ_dreamcast.sh
  utils/cmake/dreamcast.cmake
  utils/cmake/dreamcast.toolchain.cmake
Labels: enhancement, toolchain, cleanup

#524 Fixed kbd build issues due to <stdatomic> in C++
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/include/dc/maple/keyboard.h
Labels: build failure

#519 Fixed Release Build Warnings from Defining NDEBUG.
  include/sys/dirent.h
  kernel/arch/dreamcast/hardware/modem/mdata.c
  kernel/arch/dreamcast/include/dc/matrix.h
  kernel/arch/dreamcast/include/dc/net/broadband_adapter.h
  kernel/arch/dreamcast/include/dc/sq.h
  kernel/arch/dreamcast/include/dc/video.h
  kernel/arch/dreamcast/sound/snd_stream.c
  kernel/libc/koslib/readdir.c
  kernel/thread/sem.c
Labels: cleanup

#493 Allow /dev/ to exist independently of /dev/random
  examples/dreamcast/dev/Makefile
  examples/dreamcast/dev/devroot/Makefile
  examples/dreamcast/dev/devroot/devroot.c
  examples/dreamcast/dev/random/Makefile
  examples/dreamcast/dev/random/random.c
  include/kos/fs_dev.h
  include/kos/fs_null.h
  include/kos/fs_random.h
  include/kos/nmmgr.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/arch/dreamcast/kernel/initall_hdrs.h
  kernel/exports/nmmgr.c
  kernel/fs/Makefile
  kernel/fs/fs.c
  kernel/fs/fs_dev.c
  kernel/fs/fs_null.c
  kernel/fs/fs_random.c
  kernel/libc/koslib/realpath.c
Labels: enhancement, cleanup

#471 Increased Timing Resolution of pvr_stats_t
  doc/CHANGELOG
  examples/dreamcast/parallax/serpent_dma/perfmeter.c
  examples/dreamcast/parallax/serpent_dma/serpent.c
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: enhancement

#520 Dynamically Modify Scheduler Frequency HZ at Runtime
  doc/CHANGELOG
  include/kos/thread.h
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/libc/posix/sysconf.c
  kernel/thread/thread.c
Labels: enhancement

#518 Updated dc-chain for DLang + BETA m4-single support
  utils/dc-chain/config/config.mk.13.2.1-dev.sample
  utils/dc-chain/doc/changelog.txt
  utils/dc-chain/scripts/gcc-pass2.mk
Labels: enhancement, toolchain

#505 Worker threads
  doc/CHANGELOG
  include/kos/worker_thread.h
  kernel/arch/dreamcast/hardware/asic.c
  kernel/thread/Makefile
  kernel/thread/worker.c
Labels: enhancement

#530 Patch newlib headers to expose lstat
  utils/dc-chain/patches/newlib-2.0.0-kos.diff
  utils/dc-chain/patches/newlib-3.3.0-kos.diff
  utils/dc-chain/patches/newlib-4.3.0.20230120-kos.diff
  utils/dc-chain/patches/newlib-4.4.0.20231231-kos.diff
Labels: bug, help wanted, toolchain, build failure

#531 Fix 'parameter name omitted' errors on older compilers
  kernel/arch/dreamcast/hardware/maple/controller.c
  kernel/arch/dreamcast/hardware/maple/dreameye.c
  kernel/arch/dreamcast/hardware/maple/keyboard.c
  kernel/arch/dreamcast/hardware/maple/mouse.c
  kernel/arch/dreamcast/hardware/maple/purupuru.c
  kernel/arch/dreamcast/hardware/maple/sip.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
Labels: build failure

#504 Minor Floating-Point Precision Fixes
  kernel/arch/dreamcast/include/dc/vec3f.h
Labels: cleanup

#528 Makefile.rules: Add rule to create binary executables
  Makefile.rules
Labels: enhancement

#532 Add Newlib Configuration Parameter for Enabling iconv()
  utils/dc-chain/config/config.mk.14.0.1-dev.sample
  utils/dc-chain/doc/changelog.txt
  utils/dc-chain/scripts/init.mk
Labels: enhancement, toolchain
