Repository KallistiOS/KallistiOS, pull requests merged in 2024-05, with the labels that each got.

#540 Fix FIPR
  kernel/arch/dreamcast/include/dc/fmath_base.h
Labels: bug

#544 Fanalyzer ffixes
  addons/libppp/ppp.c
  kernel/arch/dreamcast/fs/vmufs.c
  kernel/arch/dreamcast/sound/snd_mem.c
  kernel/fs/fs_null.c
  kernel/fs/fs_random.c
Labels: enhancement, cleanup

#547 Forgot a closing brace in previous commit!
  kernel/fs/fs_random.c
Labels: build failure

#553 Add LRA option to environ.sh
  doc/environ.sh.sample
Labels: enhancement, documentation

#558 Dockerfile: Fix flex errors building GCC, dependency issues with GDB, and disable ARM build
  utils/dc-chain/docker/Dockerfile
Labels: bug, toolchain

#549 fb_console use memcpy4 and memset4
  kernel/arch/dreamcast/util/fb_console.c
  kernel/arch/dreamcast/util/fb_console_naomi.c
Labels: enhancement

#557 Update gitignore
  .gitignore
  utils/bincnv/Makefile
Labels: utilities

#563 Teensy Doxygen Fix for worker_thread.h.
  include/kos/worker_thread.h
Labels: documentation

#566 Avoid conditionally-compiled code & fix NAOMI build
  include/kos/platform.h
  kernel/arch/dreamcast/hardware/hardware.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/hardware/video.c
  kernel/arch/dreamcast/kernel/init.c
Labels: build failure

#536 Add Syscalls module
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/Makefile
  kernel/arch/dreamcast/hardware/biosfont.c
  kernel/arch/dreamcast/hardware/cdrom.c
  kernel/arch/dreamcast/hardware/flashrom.c
  kernel/arch/dreamcast/hardware/syscall_font.s
  kernel/arch/dreamcast/hardware/syscalls.c
  kernel/arch/dreamcast/include/dc/syscalls.h
  kernel/arch/dreamcast/kernel/init.c
Labels: enhancement, documentation, cleanup

#538 examples/dreamcast/makefile rework
  examples/dreamcast/Makefile
Labels: enhancement, example

#546 Fixed directory reading using FAM to conserve RAM
  include/sys/dirent.h
  kernel/libc/koslib/readdir.c
  kernel/libc/koslib/scandir.c
Labels: bug

#562 Fix mke2fs example with Raylib Installed
  examples/dreamcast/sd/mke2fs/Makefile
Labels: example, build failure

#571 Added Makefile Rules for Doxygen Documentation
  Makefile
Labels: enhancement, documentation

#323 Update GNU configs before dc-chain build
  utils/dc-chain/.gitignore
  utils/dc-chain/scripts/clean.mk
  utils/dc-chain/scripts/host-detect.mk
  utils/dc-chain/scripts/patch.mk
Labels: enhancement, toolchain

#572 Updated the FPU Exception Example
  examples/dreamcast/basic/fpu/exc/fpu_exc.c
Labels: enhancement, example

#568 timers: Add timer_spin_delay_{us,ns}
  doc/CHANGELOG
  kernel/arch/dreamcast/hardware/scif-spi.c
  kernel/arch/dreamcast/include/arch/timer.h
  kernel/arch/dreamcast/kernel/timer.c
Labels: enhancement

#554 Added dc-chain Configuration Option for C++'s Timezone Database
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/doc/CHANGELOG.md
  utils/dc-chain/scripts/init.mk
Labels: enhancement, toolchain

#570 Fix Cache functions
  kernel/arch/dreamcast/kernel/cache.s
Labels: bug, enhancement

#569 Linking to libm by Default in environ_base.sh.
  environ_base.sh
  examples/dreamcast/basic/breaking/Makefile
  examples/dreamcast/conio/kosh/Makefile
  examples/dreamcast/cpp/clock/Makefile
  examples/dreamcast/cpp/concurrency/Makefile
  examples/dreamcast/cpp/dcplib/Makefile
  examples/dreamcast/cpp/gltest/Makefile
  examples/dreamcast/cpp/modplug_test/Makefile
  examples/dreamcast/gldc/2D_tex_quad/Makefile
  examples/dreamcast/gldc/basic/gl/Makefile
  examples/dreamcast/gldc/basic/vq/Makefile
  examples/dreamcast/gldc/benchmarks/quadmark/Makefile
  examples/dreamcast/gldc/benchmarks/trimark/Makefile
  examples/dreamcast/gldc/benchmarks/tristripmark/Makefile
  examples/dreamcast/gldc/nehe/nehe02/Makefile
  examples/dreamcast/gldc/nehe/nehe05/Makefile
  examples/dreamcast/gldc/nehe/nehe06/Makefile
  examples/dreamcast/gldc/nehe/nehe08/Makefile
  examples/dreamcast/gldc/nehe/nehe09/Makefile
  examples/dreamcast/gldc/nehe/nehe16/Makefile
  examples/dreamcast/gldc/nehe/nehe26/Makefile
  examples/dreamcast/kgl/basic/elements/Makefile
  examples/dreamcast/kgl/basic/txrenv/Makefile
  examples/dreamcast/kgl/basic/vq/Makefile
  examples/dreamcast/kgl/basic/zclip_arrays/Makefile
  examples/dreamcast/kgl/demos/blur/Makefile
  examples/dreamcast/kgl/demos/mipmap/Makefile
  examples/dreamcast/kgl/demos/multitexture-arrays/Makefile
  examples/dreamcast/kgl/demos/multitexture-elements/Makefile
  examples/dreamcast/kgl/demos/specular/Makefile
  examples/dreamcast/kgl/nehe/nehe02/Makefile
  examples/dreamcast/kgl/nehe/nehe05/Makefile
  examples/dreamcast/kgl/nehe/nehe06/Makefile
  examples/dreamcast/kgl/nehe/nehe08/Makefile
  examples/dreamcast/kgl/nehe/nehe09/Makefile
  examples/dreamcast/kgl/nehe/nehe26/Makefile
  examples/dreamcast/lua/basic/Makefile
  examples/dreamcast/mruby/dreampresent/Makefile
  examples/dreamcast/mruby/mrbtris/Makefile
  examples/dreamcast/parallax/delay_cube/Makefile
  examples/dreamcast/parallax/font/Makefile
  examples/dreamcast/parallax/raster_melt/Makefile
  examples/dreamcast/parallax/serpent_dma/Makefile
  examples/dreamcast/parallax/sinus/Makefile
  examples/dreamcast/png/Makefile
  examples/dreamcast/rumble/Makefile
  examples/dreamcast/sound/ghettoplay-vorbis/Makefile
  examples/dreamcast/sound/hello-mp3/Makefile
  examples/dreamcast/sound/hello-ogg/Makefile
  examples/dreamcast/tsunami/banner/Makefile
  examples/dreamcast/tsunami/font/Makefile
  examples/dreamcast/tsunami/genmenu/Makefile
  examples/dreamcast/vmu/vmu_beep/Makefile
  examples/dreamcast/vmu/vmu_lcd/Makefile
Labels: update

#506 Per-thread CPU time implementation
  doc/CHANGELOG
  examples/dreamcast/basic/threading/general/general_threading_test.c
  include/kos/thread.h
  include/kos/time.h
  kernel/arch/dreamcast/include/dc/perfctr.h
  kernel/arch/dreamcast/kernel/perfctr.c
  kernel/libc/newlib/newlib_times.c
  kernel/libc/posix/clock_gettime.c
  kernel/thread/thread.c
Labels: enhancement, cleanup

#561 Bumped KOS's Default C and C++ Versions to 11
  environ_base.sh
Labels: update

#580 Stack Protector environ.sh Option + Example Tweak
  doc/environ.sh.sample
  examples/dreamcast/basic/stackprotector/stackprotector.c
  kernel/arch/dreamcast/include/arch/stack.h
Labels: enhancement, example

#585 dc-chain: Update profiles for 13.3.0 release
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/README.md
  utils/dc-chain/patches/gcc-13.3.0-kos.diff
  utils/dc-chain/patches/gcc-13.3.1-kos.diff
  utils/dc-chain/profiles/profile.13.3.0.mk
  utils/dc-chain/profiles/profile.13.3.1-dev.mk
Labels: update, toolchain

#590 Fix bad string handling in vqenc
  utils/vqenc/vqenc.c
Labels: bug, build failure

#567 Add watchdog timers + use watchdog timer in modem code
  doc/CHANGELOG
  include/kos/oneshot_timer.h
  kernel/arch/dreamcast/hardware/modem/mintern.h
  kernel/arch/dreamcast/hardware/modem/mintr.c
  kernel/arch/dreamcast/hardware/modem/modem.c
  kernel/thread/Makefile
  kernel/thread/oneshot_timer.c
Labels: enhancement, cleanup

#593 Headers
  include/kos.h
  kernel/arch/dreamcast/hardware/modem/mintr.c
Labels: cleanup

#588 Fixed Warnings from realpath() Signature Mismatches
  kernel/fs/fs.c
  kernel/libc/koslib/realpath.c
Labels: update

#598 Work around MMU issue with SQs
  kernel/arch/dreamcast/hardware/sq.c
  kernel/arch/dreamcast/include/arch/mmu.h
  kernel/arch/dreamcast/kernel/mmu.c
Labels: bug
