Repository KallistiOS/KallistiOS, pull requests merged in 2025-09, with the labels that each got.

#1181 dc-chain: Remove fake-kos.o from all libgcc.a
  utils/dc-chain/scripts/gcc-pass2.mk
Labels: bug, toolchain

#1183 Fix kos_blockdev_t created by sd_blockdev_for_device()
  kernel/arch/dreamcast/hardware/sd.c
Labels: bug

#1153 Move banner, license, authors, uname functions from arch to arch-agnostic
  include/kos/banner.h
  kernel/Makefile
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/kernel/Makefile
  kernel/arch/dreamcast/kernel/init.c
  kernel/banner.c
  kernel/libc/koslib/Makefile
  kernel/libc/koslib/uname.c
  kernel/make_authors.awk
  kernel/make_banner.sh
Labels: cleanup, build system, arch API

#1186 sys/_types: Readd `_TIME_T_` define.
  include/sys/_types.h
Labels: bug, build issues, stdlib

#1187 irq.c: Replace old `__unlikely` with newlib standard macro
  kernel/arch/dreamcast/kernel/irq.c
Labels: bug, build issues, newlib

#1196 maple: Fix race between driver attach and vblank irq
  kernel/arch/dreamcast/hardware/maple/maple_driver.c
Labels: bug, drivers

#1198 cmake: Add compatibility cmake file.
  utils/cmake/dreamcast.cmake
  utils/cmake/dreamcast.toolchain.cmake
Labels: build system

#1203 environ: Move default setting of SUBARCH to `environ_dreamcast.sh`
  doc/environ.sh.sample
  environ_dreamcast.sh
Labels: cleanup, build system

#1202 Ignore .cache/, .clangd, .envrc, and compile_commands.json
  .gitignore
Labels: cleanup, build system

#1210 g2bus: Shift to stdint types
  kernel/arch/dreamcast/hardware/g2bus.c
Labels: cleanup, build issues

#1216 `maple`: Add attribute to non-NUL-terminated strings.
  kernel/arch/dreamcast/include/dc/maple.h
Labels: cleanup

#1219 dc-chain: Update docs and mingw patch for sys/sched.h removal
  utils/dc-chain/doc/mingw/packages/fixup-sh4-newlib.sh
  utils/dc-chain/patches/README.md
Labels: toolchain, documentation, cleanup
