Repository KallistiOS/KallistiOS, pull requests merged in 2025-01, with the labels that each got.

#859 Add pvr_wait_render_done() and pvr_get_front_buffer()
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: video, drivers

#879 pvr: Do not check DMA completion in pvr_sq functions
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
Labels: bug, video

#874 PVR Function Prototypes Cleanup (pvr.h refactor #539 part 1)
  examples/dreamcast/pvr/cheap_shadow/shadow.c
  examples/dreamcast/pvr/modifier_volume_zclip/example.c
  kernel/arch/dreamcast/hardware/pvr/pvr_buffers.c
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_fog.c
  kernel/arch/dreamcast/hardware/pvr/pvr_init_shutdown.c
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_mem.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
  kernel/arch/dreamcast/include/dc/pvr.h
Labels: cleanup

#877 Convert some macros to inline functions and improve inline ASM
  kernel/arch/dreamcast/include/arch/arch.h
  kernel/arch/dreamcast/include/arch/cache.h
Labels: cleanup, optimization

#867 koslib: Drop our aligned_alloc()
  kernel/libc/c11/Makefile
  kernel/libc/c11/aligned_alloc.c
  kernel/libc/koslib/malloc.c
  kernel/libc/newlib/newlib_malloc.c
Labels: stdlib

#882 pvr_prim: Speed up header compilation
  kernel/arch/dreamcast/hardware/pvr/pvr_prim.c
Labels: video

#876 Spinlock cleanups
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/include/arch/spinlock.h
  kernel/arch/dreamcast/sound/snd_mem.c
  kernel/libc/c11/atomics.c
  kernel/mm/malloc_debug.c
  kernel/thread/tls.c
Labels: enhancement, cleanup, kernel, optimization

#884 irq: Shrink IRQ table size
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/irq.c
Labels: enhancement, kernel, optimization

#837 Speedup and fix AICA cmd iface. Protect SQs on G2 bus.
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/hardware/spu.c
  kernel/arch/dreamcast/include/dc/g2bus.h
  kernel/arch/dreamcast/include/dc/sound/aica_comm.h
  kernel/arch/dreamcast/include/dc/sound/sound.h
  kernel/arch/dreamcast/sound/arm/aica_cmd_iface.h
  kernel/arch/dreamcast/sound/snd_iface.c
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug, enhancement, audio, drivers, optimization

#889 Fix undefined references to free with lto.
  examples/dreamcast/sound/sfxbuf/main.c
Labels: example, build issues

#890 pvr: Fix dma_next_list() incorrectly unlocking mutex
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
Labels: bug, video

#893 Unhack fs dcload
  kernel/arch/dreamcast/fs/fs_dcload.c
  kernel/arch/dreamcast/include/dc/fs_dcload.h
Labels: bug, enhancement, cleanup, filesystem

#896 Fix and improve performance counters
  kernel/arch/dreamcast/kernel/perfctr.c
  kernel/arch/dreamcast/kernel/timer.c
Labels: bug, cleanup, kernel

#838 Improved sound streams data processing.
  kernel/arch/dreamcast/include/dc/sound/stream.h
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: enhancement, audio, optimization

#871 DMA Controller API
  examples/dreamcast/basic/dma/speedtest/Makefile
  examples/dreamcast/basic/dma/speedtest/speedtest.c
  kernel/arch/dreamcast/hardware/Makefile
  kernel/arch/dreamcast/hardware/dmac.c
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/scif.c
  kernel/arch/dreamcast/include/arch/dmac.h
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/irq.c
  kernel/arch/dreamcast/kernel/ser_console.c
  kernel/arch/dreamcast/kernel/timer.c
  kernel/arch/dreamcast/kernel/wdt.c
Labels: drivers

#898 vmufb: Add vmufb_paint_xbm()
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: enhancement, drivers

#900 Allow `loopstart`, `loopend` setting for `snd_sfx_play_ex`
  kernel/arch/dreamcast/include/dc/sound/sfxmgr.h
  kernel/arch/dreamcast/sound/snd_sfxmgr.c
Labels: enhancement, audio

#894 Byteswap builtins
  kernel/arch/dreamcast/include/arch/byteorder.h
Labels: cleanup, optimization

#901 Correct logic for looking up a dir in dcload_close.
  kernel/arch/dreamcast/fs/fs_dcload.c
Labels: bug, filesystem

#834 Make m4-single the default floating-point precision ABI
  doc/CHANGELOG.md
  doc/RELNOTES.md
  doc/environ.sh.sample
  environ_dreamcast.sh
  loadable/Makefile.prefab
  utils/dc-chain/Makefile.default.cfg
Labels: update, toolchain

#906 Test for NULL response from readdir.
  kernel/fs/fs.c
Labels: bug, filesystem

#870 Drop vec3f ASM
  kernel/arch/dreamcast/include/dc/vec3f.h
Labels: bug, cleanup, math

#883 IRQ Cleanup Part 3
  kernel/arch/dreamcast/include/arch/irq.h
  kernel/arch/dreamcast/kernel/irq.c
Labels: update, documentation, cleanup, kernel

#891 mmu: Add support for creating static memory maps
  doc/CHANGELOG.md
  kernel/arch/dreamcast/include/arch/mmu.h
  kernel/arch/dreamcast/kernel/mmu.c
Labels: enhancement, kernel, drivers

#910 Update GCC 15.0.0-dev profile name to GCC 15.0.1-dev
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/README.md
  utils/dc-chain/docker/README.md
  utils/dc-chain/patches/gcc-15.0.1-kos.diff
  utils/dc-chain/profiles/profile.15.0.1-dev.mk
Labels: update, toolchain

#914 Fixed build issue in irq.c.
  kernel/arch/dreamcast/kernel/irq.c
Labels: bug, build issues, kernel

#905 doc: CHANGELOG: Add entry about DMAC API
  doc/CHANGELOG.md
  kernel/arch/dreamcast/hardware/dmac.c
Labels: documentation

#921 Add raytris raylib example
  doc/CHANGELOG.md
  examples/dreamcast/raylib/raytris/Makefile
  examples/dreamcast/raylib/raytris/README.md
  examples/dreamcast/raylib/raytris/romdisk/assets/sound/bgm.adpcm
  examples/dreamcast/raylib/raytris/romdisk/assets/sound/clear.wav
  examples/dreamcast/raylib/raytris/romdisk/assets/sound/rotate.wav
  examples/dreamcast/raylib/raytris/src/blocks/block.cpp
  examples/dreamcast/raylib/raytris/src/blocks/block.h
  examples/dreamcast/raylib/raytris/src/blocks/blocks.cpp
  examples/dreamcast/raylib/raytris/src/colors/colors.cpp
  examples/dreamcast/raylib/raytris/src/colors/colors.h
  examples/dreamcast/raylib/raytris/src/constants/constants.h
  examples/dreamcast/raylib/raytris/src/constants/vmuIcons.cpp
  examples/dreamcast/raylib/raytris/src/constants/vmuIcons.h
  examples/dreamcast/raylib/raytris/src/game/game.cpp
  examples/dreamcast/raylib/raytris/src/game/game.h
  examples/dreamcast/raylib/raytris/src/grid/grid.cpp
  examples/dreamcast/raylib/raytris/src/grid/grid.h
  examples/dreamcast/raylib/raytris/src/position/position.cpp
  examples/dreamcast/raylib/raytris/src/position/position.h
  examples/dreamcast/raylib/raytris/src/raytris.cpp
  examples/dreamcast/raylib/raytris/src/sound/soundManager.cpp
  examples/dreamcast/raylib/raytris/src/sound/soundManager.h
  examples/dreamcast/raylib/raytris/src/system/cd.h
  examples/dreamcast/raylib/raytris/src/vmu/vmuManager.cpp
  examples/dreamcast/raylib/raytris/src/vmu/vmuManager.h
  examples/dreamcast/raylib/tetris/Makefile
  examples/dreamcast/raylib/tetris/README.md
  examples/dreamcast/raylib/tetris/romdisk/assets/sound/bgm.adpcm
  examples/dreamcast/raylib/tetris/romdisk/assets/sound/clear.wav
  examples/dreamcast/raylib/tetris/romdisk/assets/sound/rotate.wav
  examples/dreamcast/raylib/tetris/src/blocks/block.cpp
  examples/dreamcast/raylib/tetris/src/blocks/block.h
  examples/dreamcast/raylib/tetris/src/blocks/blocks.cpp
  examples/dreamcast/raylib/tetris/src/colors/colors.cpp
  examples/dreamcast/raylib/tetris/src/colors/colors.h
  examples/dreamcast/raylib/tetris/src/constants/constants.h
  examples/dreamcast/raylib/tetris/src/constants/vmuIcons.cpp
  examples/dreamcast/raylib/tetris/src/constants/vmuIcons.h
  examples/dreamcast/raylib/tetris/src/game/game.cpp
  examples/dreamcast/raylib/tetris/src/game/game.h
  examples/dreamcast/raylib/tetris/src/grid/grid.cpp
  examples/dreamcast/raylib/tetris/src/grid/grid.h
  examples/dreamcast/raylib/tetris/src/position/position.cpp
  examples/dreamcast/raylib/tetris/src/position/position.h
  examples/dreamcast/raylib/tetris/src/sound/soundManager.cpp
  examples/dreamcast/raylib/tetris/src/sound/soundManager.h
  examples/dreamcast/raylib/tetris/src/tetris.cpp
  examples/dreamcast/raylib/tetris/src/vmu/vmuManager.cpp
  examples/dreamcast/raylib/tetris/src/vmu/vmuManager.h
  examples/dreamcast/readme.md
Labels: example

#917 Added PantherDC to Controller Capability Typelist
  kernel/arch/dreamcast/include/dc/maple/controller.h
Labels: enhancement, drivers

#924 Added support for more queries to sysconf().
  kernel/libc/posix/sysconf.c
Labels: enhancement

#916 Updated AUTHORS with year 2025 for Falco Girgis.
  AUTHORS
Labels: documentation

#918 Added thread attribs to cont_btn_callback worker.
  kernel/arch/dreamcast/hardware/maple/controller.c
Labels: enhancement, drivers, optimization

#920 Fix type clash in vmu example.
  examples/dreamcast/libdream/vmu/vmu.c
Labels: example, build issues

#927 Remove duplicated copy of the raytris example.
  examples/dreamcast/raylib/tetris/Makefile
  examples/dreamcast/raylib/tetris/README.md
  examples/dreamcast/raylib/tetris/romdisk/assets/sound/bgm.adpcm
  examples/dreamcast/raylib/tetris/romdisk/assets/sound/clear.wav
  examples/dreamcast/raylib/tetris/romdisk/assets/sound/rotate.wav
  examples/dreamcast/raylib/tetris/src/blocks/block.cpp
  examples/dreamcast/raylib/tetris/src/blocks/block.h
  examples/dreamcast/raylib/tetris/src/blocks/blocks.cpp
  examples/dreamcast/raylib/tetris/src/colors/colors.cpp
  examples/dreamcast/raylib/tetris/src/colors/colors.h
  examples/dreamcast/raylib/tetris/src/constants/constants.h
  examples/dreamcast/raylib/tetris/src/constants/vmuIcons.cpp
  examples/dreamcast/raylib/tetris/src/constants/vmuIcons.h
  examples/dreamcast/raylib/tetris/src/game/game.cpp
  examples/dreamcast/raylib/tetris/src/game/game.h
  examples/dreamcast/raylib/tetris/src/grid/grid.cpp
  examples/dreamcast/raylib/tetris/src/grid/grid.h
  examples/dreamcast/raylib/tetris/src/position/position.cpp
  examples/dreamcast/raylib/tetris/src/position/position.h
  examples/dreamcast/raylib/tetris/src/sound/soundManager.cpp
  examples/dreamcast/raylib/tetris/src/sound/soundManager.h
  examples/dreamcast/raylib/tetris/src/tetris.cpp
  examples/dreamcast/raylib/tetris/src/vmu/vmuManager.cpp
  examples/dreamcast/raylib/tetris/src/vmu/vmuManager.h
Labels: cleanup, example

#925 pvr: random cleanups and IRQ race fix in dma_next_list()
  kernel/arch/dreamcast/hardware/pvr/pvr_buffers.c
  kernel/arch/dreamcast/hardware/pvr/pvr_dma.c
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
Labels: bug, cleanup, video
