Repository KallistiOS/KallistiOS, pull requests merged in 2025-05, with the labels that each got.

#982 maple: Fix maple_enum_type()
  kernel/arch/dreamcast/hardware/maple/maple_enum.c
Labels: bug, drivers

#985 Update gitignore to ignore intermediate bin2c file.
  .gitignore
Labels: cleanup

#979 `dc-chain`: adding GCC 9.5.0 patches for MinGW-w64/MSYS2
  utils/dc-chain/patches/i686-w64-mingw32/gcc-9.5.0.diff
  utils/dc-chain/patches/x86_64-w64-mingw32/gcc-9.5.0.diff
Labels: toolchain

#988 sd: Optimized reading and writing sectors on SCIF-SPI.
  kernel/arch/dreamcast/hardware/sd.c
Labels: enhancement, drivers, optimization, Mods

#981 pvr: Move + improve PVR poly headers and types into their own file
  kernel/arch/dreamcast/include/dc/pvr.h
  kernel/arch/dreamcast/include/dc/pvr/pvr_header.h
Labels: enhancement, documentation, video

#971 maple: Support multiple hotplug callbacks
  kernel/arch/dreamcast/hardware/maple/maple_driver.c
  kernel/arch/dreamcast/include/dc/maple.h
Labels: enhancement, drivers

#680 Another round of KOS_INIT_FLAG() modularization.
  include/kos/fs_dev.h
  include/kos/fs_null.h
  include/kos/fs_pty.h
  include/kos/fs_ramdisk.h
  include/kos/fs_random.h
  include/kos/init.h
  include/kos/library.h
  kernel/arch/dreamcast/include/arch/init_flags.h
  kernel/arch/dreamcast/kernel/init.c
  kernel/exports/library.c
  kernel/fs/fs_dev.c
  kernel/fs/fs_null.c
  kernel/fs/fs_pty.c
  kernel/fs/fs_ramdisk.c
  kernel/fs/fs_random.c
Labels: enhancement, filesystem

#541 Allow the patched toolchain to support -m4-nofpu
  kernel/arch/dreamcast/kernel/startup.S
  utils/dc-chain/Makefile.default.cfg
  utils/dc-chain/scripts/patch.mk
Labels: enhancement, toolchain

#994 Add missing include in sci
  kernel/arch/dreamcast/hardware/sci.c
Labels: bug, build issues

#998 Add dummy char in pthread_barrierattr_t and pthread_rwlockattr_t
  include/sys/_pthreadtypes.h
Labels: build issues

#997 Fix mismatched types for ubc callback.
  examples/dreamcast/basic/breaking/breaking.c
  kernel/arch/dreamcast/include/dc/ubc.h
Labels: cleanup, build issues

#1005 Roll back bad pointer math update for arch_exec_at.
  kernel/arch/dreamcast/kernel/exec.c
Labels: bug, kernel

#1002 Fix printf format types for pvr_stats members in GL examples.
  examples/dreamcast/gldc/basic/gl/gltest.c
  examples/dreamcast/gldc/benchmarks/quadmark/quadmark.c
  examples/dreamcast/gldc/benchmarks/trimark/trimark.c
  examples/dreamcast/gldc/benchmarks/tristripmark/tristripmark.c
Labels: cleanup, example

#1001 CI: Automatically sync to SourceForge
  .github/workflows/sourceforge.yml
Labels: build system

#1008 Include arch/types.h in thread.h to fix toolchain building
  include/kos/thread.h
Labels: toolchain, build issues

#1013 Remove erroneous Makefile from examples/dreamcast/pthread
  examples/dreamcast/pthread/Makefile
Labels: cleanup, example, build issues

#1014 Restore struct packing to network structs that were removed
  include/kos/net.h
  kernel/net/net_arp.c
  kernel/net/net_dhcp.h
  kernel/net/net_icmp.h
  kernel/net/net_icmp6.h
  kernel/net/net_ipv4.h
  kernel/net/net_ipv6.h
  kernel/net/net_tcp.c
  kernel/net/net_udp.c
Labels: bug, networking

#1016 scif: disable MCE by default
  kernel/arch/dreamcast/hardware/scif.c
Labels: bug, drivers

#1020 `fs_ramdisk_create` OoM
  kernel/fs/fs_ramdisk.c
Labels: bug, cleanup, filesystem

#1019 Fix use-after-free in `fs_close`.
  kernel/fs/fs.c
Labels: bug, filesystem

#1018 Clean up `pvr_init_params_t` usage in examples.
  examples/dreamcast/2ndmix/2ndmix.c
  examples/dreamcast/cpp/clock/clock.cc
  examples/dreamcast/cpp/dcplib/fnt_test.cc
  examples/dreamcast/gldc/benchmarks/quadmark/quadmark.c
  examples/dreamcast/gldc/benchmarks/trimark/trimark.c
  examples/dreamcast/gldc/benchmarks/tristripmark/tristripmark.c
  examples/dreamcast/kgl/basic/scissor/scissor.c
  examples/dreamcast/kgl/benchmarks/quadmark/quadmark.c
  examples/dreamcast/kgl/benchmarks/trimark/trimark.c
  examples/dreamcast/kgl/benchmarks/tristripmark/tristripmark.c
  examples/dreamcast/libdream/ta/ta.c
  examples/dreamcast/parallax/bubbles/bubbles.c
  examples/dreamcast/parallax/serpent_dma/serpent.c
  examples/dreamcast/pvr/bumpmap/bump.c
  examples/dreamcast/pvr/cheap_shadow/shadow.c
  examples/dreamcast/pvr/modifier_volume/modifier.c
  examples/dreamcast/pvr/modifier_volume_tex/modifier.c
  examples/dreamcast/pvr/pvrline/pvrline.c
  examples/dreamcast/pvr/pvrmark/pvrmark.c
  examples/dreamcast/pvr/pvrmark_strips/pvrmark_strips.c
  examples/dreamcast/pvr/pvrmark_strips_direct/pvrmark_strips_direct.c
  examples/dreamcast/pvr/texture_render/texture_render.c
Labels: cleanup, example

#1017 mrbtris: Fix incompatible type error
  examples/dreamcast/mruby/mrbtris/dckos.c
Labels: bug, example

#1027 Fix missing include in speedtest.
  examples/dreamcast/filesystem/sd/speedtest/sd-speedtest.c
Labels: cleanup, example, build issues

#1021 `libkosext2fs`: Ensure buffer can store uint32s.
  addons/libkosext2fs/inode.c
Labels: bug, cleanup, filesystem, Mods

#1024 Move gitignore declarations to sub-project dirs
  .gitignore
  examples/dreamcast/basic/exec/.gitignore
  examples/dreamcast/conio/adventure/.gitignore
  examples/dreamcast/gldc/basic/vq/.gitignore
  examples/dreamcast/gldc/nehe/nehe26/.gitignore
  examples/dreamcast/kgl/basic/vq/.gitignore
  examples/dreamcast/kgl/nehe/nehe26/.gitignore
  examples/dreamcast/library/.gitignore
  examples/dreamcast/png/.gitignore
  examples/dreamcast/pvr/bumpmap/.gitignore
  examples/dreamcast/pvr/modifier_volume_tex/.gitignore
  examples/dreamcast/pvr/texture_render/.gitignore
  examples/dreamcast/video/screenshot/.gitignore
  kernel/arch/dreamcast/kernel/.gitignore
  kernel/arch/dreamcast/sound/.gitignore
  kernel/arch/dreamcast/sound/arm/.gitignore
  kernel/exports/.gitignore
  kernel/stubs/.gitignore
  utils/bin2c/.gitignore
  utils/bincnv/.gitignore
  utils/dcbumpgen/.gitignore
  utils/genromfs/.gitignore
  utils/gentexfont/.gitignore
  utils/isotest/.gitignore
  utils/kmgenc/.gitignore
  utils/makeip/.gitignore
  utils/makejitter/.gitignore
  utils/naomibintool/.gitignore
  utils/naominetboot/.gitignore
  utils/scramble/.gitignore
  utils/vqenc/.gitignore
  utils/wav2adpcm/.gitignore
Labels: cleanup

#1030 Fix warnings previously hidden behind ifdef guards
  kernel/arch/dreamcast/fs/fs_vmu.c
  kernel/fs/elf.c
Labels: cleanup

#1006 Deprecate `snd_stream_prefill`
  kernel/arch/dreamcast/exports-naomi.txt
  kernel/arch/dreamcast/exports-pristine.txt
  kernel/arch/dreamcast/include/dc/sound/stream.h
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug, audio

#1032 Add additional check for m4-single ABI support to fix DreamSDK issues
  environ_dreamcast.sh
Labels: enhancement, build issues

#1036 pvr: Get rid of dummy fields in prim headers
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_prim.c
  kernel/arch/dreamcast/include/dc/pvr/pvr_header.h
Labels: bug, video

#1041 Add missing DECLS to pthreads and sys headers.
  addons/libpthread/pthread-internal.h
  include/sys/_pthreadtypes.h
  include/sys/lock.h
  include/sys/stdio.h
Labels: bug, cleanup

#1050 Correct logical error in snd_stream double init protection.
  kernel/arch/dreamcast/sound/snd_stream.c
Labels: bug, audio

#1055 Correct `mutex_trylock` errno.
  include/kos/mutex.h
  kernel/libc/c11/mtx_trylock.c
  kernel/thread/mutex.c
Labels: bug, kernel, stdlib

#1057 Add pthread include to fix 9.5.0-winxp profile.
  utils/dc-chain/patches/gcc/gthr-kos.h
Labels: bug, toolchain
