Repository KallistiOS/KallistiOS, pull requests merged in 2025-02, with the labels that each got.

#899 Ensure sq_writeback is flagged as causing memory to change.
  kernel/arch/dreamcast/include/arch/cache.h
Labels: bug, kernel

#913 Deprecated string.h and removed usages.
  examples/dreamcast/vmu/vmu_game/vmu_game.c
  examples/dreamcast/vmu/vmu_pkg/vmu.c
  include/kos/string.h
  kernel/arch/dreamcast/hardware/maple/maple_utils.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
  kernel/arch/dreamcast/hardware/pvr/pvr_texture.c
  kernel/arch/dreamcast/util/fb_console.c
  kernel/arch/dreamcast/util/fb_console_naomi.c
Labels: bug, documentation, utilities

#915 VMU Button Bitflag Fix, Plus Maintaining Previous Button States.
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/maple/vmu.h
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: enhancement, drivers

#922 `dc-chain` update documentations
  utils/dc-chain/README.md
  utils/dc-chain/doc/CHANGELOG.md
  utils/dc-chain/doc/CONTRIBUTORS.md
  utils/dc-chain/doc/alpine.md
  utils/dc-chain/doc/bsd.md
  utils/dc-chain/doc/cygwin.md
  utils/dc-chain/doc/debian.md
  utils/dc-chain/doc/macos.md
  utils/dc-chain/doc/mingw/README.md
  utils/dc-chain/doc/mingw/mingw-w64.md
  utils/dc-chain/doc/mingw/mingw.md
  utils/dc-chain/patches/x86_64-w64-mingw32/gcc-8.5.0.diff
Labels: toolchain, documentation

#873 vmu_pkg: Add function to load VMU icons from .ico files
  examples/dreamcast/vmu/vmu_pkg/Makefile
  examples/dreamcast/vmu/vmu_pkg/romdisk/ebook.ico
  examples/dreamcast/vmu/vmu_pkg/vmu.c
  kernel/arch/dreamcast/include/dc/vmu_pkg.h
  kernel/arch/dreamcast/util/vmu_pkg.c
Labels: enhancement, example, utilities, filesystem

#933 Remove redefined 'BSD-style' types.
  examples/dreamcast/conio/wump/wump.c
  kernel/arch/dreamcast/include/arch/types.h
Labels: cleanup, stdlib

#804 Persist allocated `maple_device_t`s
  examples/dreamcast/rumble/rumble.c
  kernel/arch/dreamcast/hardware/maple/maple_driver.c
  kernel/arch/dreamcast/hardware/maple/maple_enum.c
  kernel/arch/dreamcast/hardware/maple/maple_init_shutdown.c
  kernel/arch/dreamcast/hardware/maple/maple_irq.c
  kernel/arch/dreamcast/include/dc/maple.h
Labels: bug, update, drivers

#932 Right-size the pcaps buffer.
  kernel/arch/dreamcast/hardware/maple/maple_utils.c
Labels: optimization

#911 Ansi cleanups
  addons/libnavi/navi_flash.c
  addons/libnavi/navi_ide.c
  include/sys/_pthread.h
  include/sys/_types.h
  include/sys/lock.h
  kernel/arch/dreamcast/include/dc/scif.h
  kernel/arch/dreamcast/include/dc/video.h
  kernel/libc/koslib/readdir.c
Labels: cleanup

#938 asic: Add ability to set a chain of handlers for IRQ's.
  kernel/arch/dreamcast/hardware/asic.c
  kernel/arch/dreamcast/include/dc/asic.h
Labels: enhancement, kernel

#929 cache: Fix non-working dcache_{flush,purge}_all()
  kernel/arch/dreamcast/kernel/cache.s
Labels: bug, kernel

#907 Vmu pkg cleaning
  kernel/arch/dreamcast/include/dc/vmu_pkg.h
  kernel/arch/dreamcast/util/vmu_pkg.c
Labels: cleanup

#936 isofs: Short-circuit the cache and use multi-sector reads if possible.
  kernel/arch/dreamcast/fs/fs_iso9660.c
Labels: enhancement, filesystem, optimization

#943 Correct erroneous resetting of output buffer in vmu_pkg_build.
  kernel/arch/dreamcast/util/vmu_pkg.c
Labels: bug
