Repository KallistiOS/KallistiOS, pull requests merged in 2025-06, with the labels that each got.

#1062 Fixed Potential Racing when Accessing IRQ/TRAPA Handlers
  kernel/arch/dreamcast/kernel/irq.c
Labels: bug, kernel

#1068 Update gitignore to ignore generated `authors.h`
  kernel/arch/dreamcast/kernel/.gitignore
Labels: cleanup

#1080 Fix barrier example
  examples/dreamcast/basic/threading/barrier/barrier.c
Labels: bug, example

#1058 Fix various warnings in examples.
  examples/dreamcast/2ndmix/2ndmix.c
  examples/dreamcast/basic/breaking/breaking.c
  examples/dreamcast/basic/mmu/nullptr/nullptr.c
  examples/dreamcast/cdrom/stream/cd-stream-test.c
  examples/dreamcast/cpp/concurrency/concurrency.cpp
  examples/dreamcast/gldc/basic/vq/vq-example.c
  examples/dreamcast/gldc/nehe/nehe26/nehe26.c
  examples/dreamcast/sound/ghettoplay-vorbis/songmenu.c
Labels: bug, cleanup, example

#1077 cdrom: Factorize and fix commands taking way too much time
  kernel/arch/dreamcast/hardware/cdrom.c
Labels: drivers

#1078 Map keyboard 'return' key to CR not LF.
  kernel/arch/dreamcast/hardware/maple/keyboard.c
Labels: bug, drivers

#1071 Fix toolchain compilation on recent macOS using Apple Clang 17
  utils/dc-chain/scripts/init.mk
Labels: bug, toolchain

#1086 dc-chain: Make GDB CPATH and LIBRARY_PATH exports for macOS conditional
  utils/dc-chain/scripts/gdb.mk
Labels: toolchain, build system

#1087 Fixes for doxygen warnings
  include/pthread.h
  kernel/arch/dreamcast/include/dc/maple/keyboard.h
  kernel/arch/dreamcast/include/dc/maple/vmu.h
Labels: bug, documentation, cleanup

#1088 examples: replace `.keepme` with `.gitignore`
  Makefile.rules
  examples/dreamcast/basic/exec/.gitignore
  examples/dreamcast/basic/exec/romdisk/.gitignore
  examples/dreamcast/basic/exec/romdisk/.keepme
  examples/dreamcast/cpp/modplug_test/romdisk/.keepme
  examples/dreamcast/pvr/bumpmap/.gitignore
  examples/dreamcast/pvr/bumpmap/romdisk/.gitignore
  examples/dreamcast/pvr/bumpmap/romdisk/.keepme
  examples/dreamcast/sound/ghettoplay-vorbis/romdisk/.gitignore
  examples/dreamcast/sound/ghettoplay-vorbis/romdisk/.keepme
  examples/dreamcast/sound/hello-adx/romdisk/.gitignore
  examples/dreamcast/sound/hello-adx/romdisk/.keepme
  examples/dreamcast/sound/hello-mp3/romdisk/.gitignore
  examples/dreamcast/sound/hello-mp3/romdisk/.keepme
  examples/dreamcast/sound/hello-ogg/romdisk/.gitignore
  examples/dreamcast/sound/hello-ogg/romdisk/.keepme
  examples/dreamcast/sound/hello-opus/romdisk/.gitignore
  examples/dreamcast/sound/hello-opus/romdisk/.keepme
Labels: cleanup, build system
