Repository KallistiOS/KallistiOS, pull requests merged in 2025-04, with the labels that each got.

#959 Fix CDDA on GDEMU clones
  kernel/arch/dreamcast/hardware/cdrom.c
Labels: bug, drivers, Mods

#958 pvr_list_prim(): avoid buffer overflow
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
Labels: bug, video

#960 math: Add mat_multiply()
  kernel/arch/dreamcast/include/dc/matrix.h
  kernel/arch/dreamcast/math/matrix.s
Labels: math

#961 vmufb: Add function vmufb_screen_shot()
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: drivers

#962 pvr: Fix render-to-texture
  kernel/arch/dreamcast/hardware/pvr/pvr_internal.h
  kernel/arch/dreamcast/hardware/pvr/pvr_irq.c
  kernel/arch/dreamcast/hardware/pvr/pvr_misc.c
  kernel/arch/dreamcast/hardware/pvr/pvr_scene.c
Labels: bug, video

#967 g1ata: Fixed max sector count and LBA28 DMA chaining.
  kernel/arch/dreamcast/hardware/g1ata.c
Labels: drivers, Mods

#969 libc: Fix thrd_join()
  kernel/libc/c11/thrd_join.c
Labels: kernel, stdlib

#973 fs_iso9660: Get rid of global FD table
  kernel/arch/dreamcast/fs/fs_iso9660.c
Labels: enhancement, filesystem

#977 sound: Fix loading of ARM firmware
  kernel/arch/dreamcast/sound/Makefile
  kernel/arch/dreamcast/sound/snd_iface.c
Labels: bug, cleanup
