Repository KallistiOS/KallistiOS, pull requests merged in 2025-07, with the labels that each got.

#1089 Fix built object file not added to the KOS library
  kernel/Makefile
Labels: bug, build system

#983 dmac: Drop old DMAC interface and header
  kernel/arch/dreamcast/hardware/dmac.c
  kernel/arch/dreamcast/include/dc/dmac.h
  kernel/arch/dreamcast/kernel/init.c
Labels: cleanup, kernel, drivers, NAOMI

#1090 dc-chain: Change source URL for config.guess and config.sub to more reliable mirror
  utils/dc-chain/scripts/host-detect.mk
Labels: toolchain

#763 isofs: Added cdrom streams and direct DMA support
  include/sys/ioctl.h
  kernel/arch/dreamcast/fs/fs_iso9660.c
Labels: enhancement, filesystem, drivers

#1093 pvr: Extend VRAM to 16 MiB on Naomi
  kernel/arch/dreamcast/include/dc/pvr/pvr_regs.h
Labels: video, NAOMI

#1101 vmulcd: Correct data types of vmu fb.
  examples/dreamcast/vmu/vmu_lcd/lcd.c
  kernel/arch/dreamcast/include/dc/vmu_fb.h
  kernel/arch/dreamcast/util/vmu_fb.c
Labels: bug, example, drivers

#1102 net: Replace `arch/types.h` types with stdint.
  include/kos/net.h
  kernel/net/net_arp.c
  kernel/net/net_core.c
  kernel/net/net_crc.c
  kernel/net/net_dhcp.c
  kernel/net/net_dhcp.h
  kernel/net/net_icmp.c
  kernel/net/net_icmp.h
  kernel/net/net_icmp6.c
  kernel/net/net_icmp6.h
  kernel/net/net_input.c
  kernel/net/net_ipv4.c
  kernel/net/net_ipv4.h
  kernel/net/net_ipv4_frag.c
  kernel/net/net_ipv6.c
  kernel/net/net_ipv6.h
  kernel/net/net_multicast.c
  kernel/net/net_ndp.c
  kernel/net/net_tcp.c
  kernel/net/net_thd.c
  kernel/net/net_thd.h
  kernel/net/net_udp.c
Labels: cleanup, networking

#1035 Added CMake installation include paths for KOS-ports to toolchain.
  utils/cmake/dreamcast.toolchain.cmake
Labels: enhancement, utilities, build system

#1105 CMake: Use absolute path for KOS variables
  utils/cmake/dreamcast.toolchain.cmake
Labels: build system

#1107 CMake: Set default installation directories only if not defined
  utils/cmake/dreamcast.toolchain.cmake
Labels: build system

#1109 Add missing include path for architecture-specific addons
  environ_base.sh
Labels: build system

#904 Don't block for rumble and vmu beep/screen commands
  kernel/arch/dreamcast/hardware/maple/purupuru.c
  kernel/arch/dreamcast/hardware/maple/vmu.c
  kernel/arch/dreamcast/include/dc/maple/purupuru.h
  kernel/arch/dreamcast/include/dc/maple/vmu.h
Labels: update, drivers
